const alice_small = {
    "vertices": ["said", "the", "of", "alice", "in", "a", "and", "it", "was", "to", "king", "queen", "as", "she", "had", "at", "little", "gryphon", "mock", "turtle", "hatter", "herself", "be", "went", "on", "duchess", "thought", "out", "there", "dormouse", "her", "with", "that", "i", "don't", "then", "march", "hare", "other", "well", "could", "so", "did", "not", "mouse", "up", "such", "all", "caterpillar", "very", "into", "one", "you", "know", "see", "but", "if", "white", "same", "get", "by", "rabbit", "cat", "do", "large", "say", "are", "seemed", "won't", "door", "shall", "think", "when", "it'", "should", "wish", "go", "been", "for", "last", "will", "first", "have", "course", "is", "great", "would", "looked", "like", "must", "know'", "head", "once", "this", "time", "they", "were", "next", "can", "them", "minute", "again", "sort", "two", "or", "am", "jury", "can't", "good", "just", "whole", "dodo", "cook", "court", "find", "began", "found", "felt", "what", "long", "he", "about", "back", "way", "pigeon", "never", "down", "soon", "some", "ought", "going", "tell", "baby", "right", "end", "house", "heard", "come", "poor", "used", "an", "air", "words", "moment", "knave", "wonder", "replied", "make", "now", "low", "took", "off", "near", "your", "majesty'", "while", "there's", "no", "you'", "till", "turning", "my", "table", "garden", "dance", "speak", "much", "tried", "use", "his", "after", "from", "got", "dear", "i'm", "who", "sat", "set", "join", "top", "pool", "best", "rest", "suppose", "quite", "listen", "its", "sight", "their", "how", "ran", "came", "might", "any", "before", "look", "put", "which", "let", "me", "that's", "through", "among", "it's", "round", "trying", "cried", "beautiful", "soup", "another", "distance", "reason", "footman", "three", "queen's", "game", "hadn't", "beginning", "ask", "work", "begin", "hearts", "sister", "face", "knew", "doesn't", "thing", "over", "under", "that'", "here", "upon", "deal", "seem", "sure", "saying", "hand", "rate", "gloves", "fan", "tone", "indeed'", "called", "looking", "added", "world", "name", "roof", "middle", "sea", "lory", "trees", "soldiers", "executioner", "moral", "only", "beg", "sitting", "change", "grow", "course'", "hands", "is'", "curious", "hard"],
    "edges": [{
        "source": "said",
        "target": "the",
        "weight": 209
    }, {
        "source": "of",
        "target": "the",
        "weight": 130
    }, {
        "source": "said",
        "target": "alice",
        "weight": 125
    }, {
        "source": "in",
        "target": "a",
        "weight": 97
    }, {
        "source": "and",
        "target": "the",
        "weight": 80
    }, {
        "source": "in",
        "target": "the",
        "weight": 79
    }, {
        "source": "it",
        "target": "was",
        "weight": 70
    }, {
        "source": "to",
        "target": "the",
        "weight": 69
    }, {
        "source": "the",
        "target": "king",
        "weight": 65
    }, {
        "source": "the",
        "target": "queen",
        "weight": 64
    }, {
        "source": "as",
        "target": "she",
        "weight": 61
    }, {
        "source": "she",
        "target": "had",
        "weight": 60
    }, {
        "source": "at",
        "target": "the",
        "weight": 60
    }, {
        "source": "a",
        "target": "little",
        "weight": 58
    }, {
        "source": "she",
        "target": "was",
        "weight": 56
    }, {
        "source": "the",
        "target": "gryphon",
        "weight": 55
    }, {
        "source": "mock",
        "target": "turtle",
        "weight": 54
    }, {
        "source": "the",
        "target": "mock",
        "weight": 53
    }, {
        "source": "and",
        "target": "she",
        "weight": 53
    }, {
        "source": "the",
        "target": "hatter",
        "weight": 51
    }, {
        "source": "to",
        "target": "herself",
        "weight": 49
    }, {
        "source": "to",
        "target": "be",
        "weight": 49
    }, {
        "source": "went",
        "target": "on",
        "weight": 48
    }, {
        "source": "the",
        "target": "duchess",
        "weight": 39
    }, {
        "source": "said",
        "target": "to",
        "weight": 39
    }, {
        "source": "thought",
        "target": "alice",
        "weight": 38
    }, {
        "source": "out",
        "target": "of",
        "weight": 37
    }, {
        "source": "alice",
        "target": "and",
        "weight": 35
    }, {
        "source": "there",
        "target": "was",
        "weight": 35
    }, {
        "source": "on",
        "target": "the",
        "weight": 34
    }, {
        "source": "she",
        "target": "said",
        "weight": 34
    }, {
        "source": "the",
        "target": "dormouse",
        "weight": 33
    }, {
        "source": "to",
        "target": "her",
        "weight": 33
    }, {
        "source": "with",
        "target": "the",
        "weight": 33
    }, {
        "source": "that",
        "target": "she",
        "weight": 33
    }, {
        "source": "i",
        "target": "don't",
        "weight": 31
    }, {
        "source": "alice",
        "target": "to",
        "weight": 31
    }, {
        "source": "was",
        "target": "a",
        "weight": 31
    }, {
        "source": "and",
        "target": "then",
        "weight": 31
    }, {
        "source": "march",
        "target": "hare",
        "weight": 31
    }, {
        "source": "the",
        "target": "other",
        "weight": 30
    }, {
        "source": "the",
        "target": "march",
        "weight": 30
    }, {
        "source": "it",
        "target": "and",
        "weight": 30
    }, {
        "source": "as",
        "target": "well",
        "weight": 30
    }, {
        "source": "she",
        "target": "could",
        "weight": 29
    }, {
        "source": "she",
        "target": "went",
        "weight": 29
    }, {
        "source": "so",
        "target": "she",
        "weight": 29
    }, {
        "source": "as",
        "target": "it",
        "weight": 28
    }, {
        "source": "did",
        "target": "not",
        "weight": 28
    }, {
        "source": "the",
        "target": "mouse",
        "weight": 27
    }, {
        "source": "up",
        "target": "and",
        "weight": 27
    }, {
        "source": "with",
        "target": "a",
        "weight": 27
    }, {
        "source": "such",
        "target": "a",
        "weight": 27
    }, {
        "source": "could",
        "target": "not",
        "weight": 26
    }, {
        "source": "all",
        "target": "the",
        "weight": 26
    }, {
        "source": "caterpillar",
        "target": "the",
        "weight": 26
    }, {
        "source": "a",
        "target": "very",
        "weight": 25
    }, {
        "source": "into",
        "target": "the",
        "weight": 24
    }, {
        "source": "one",
        "target": "of",
        "weight": 24
    }, {
        "source": "you",
        "target": "know",
        "weight": 24
    }, {
        "source": "to",
        "target": "see",
        "weight": 23
    }, {
        "source": "she",
        "target": "thought",
        "weight": 23
    }, {
        "source": "but",
        "target": "she",
        "weight": 23
    }, {
        "source": "that",
        "target": "it",
        "weight": 23
    }, {
        "source": "you",
        "target": "if",
        "weight": 23
    }, {
        "source": "the",
        "target": "white",
        "weight": 22
    }, {
        "source": "the",
        "target": "same",
        "weight": 22
    }, {
        "source": "to",
        "target": "get",
        "weight": 22
    }, {
        "source": "by",
        "target": "the",
        "weight": 22
    }, {
        "source": "but",
        "target": "it",
        "weight": 22
    }, {
        "source": "white",
        "target": "rabbit",
        "weight": 22
    }, {
        "source": "the",
        "target": "cat",
        "weight": 21
    }, {
        "source": "to",
        "target": "do",
        "weight": 21
    }, {
        "source": "and",
        "target": "was",
        "weight": 21
    }, {
        "source": "a",
        "target": "large",
        "weight": 21
    }, {
        "source": "say",
        "target": "to",
        "weight": 21
    }, {
        "source": "at",
        "target": "all",
        "weight": 21
    }, {
        "source": "are",
        "target": "you",
        "weight": 21
    }, {
        "source": "do",
        "target": "you",
        "weight": 20
    }, {
        "source": "seemed",
        "target": "to",
        "weight": 20
    }, {
        "source": "you",
        "target": "won't",
        "weight": 20
    }, {
        "source": "in",
        "target": "her",
        "weight": 19
    }, {
        "source": "the",
        "target": "door",
        "weight": 19
    }, {
        "source": "i",
        "target": "shall",
        "weight": 19
    }, {
        "source": "i",
        "target": "think",
        "weight": 19
    }, {
        "source": "was",
        "target": "the",
        "weight": 19
    }, {
        "source": "of",
        "target": "a",
        "weight": 19
    }, {
        "source": "as",
        "target": "the",
        "weight": 19
    }, {
        "source": "when",
        "target": "she",
        "weight": 19
    }, {
        "source": "it'",
        "target": "said",
        "weight": 19
    }, {
        "source": "the",
        "target": "rabbit",
        "weight": 18
    }, {
        "source": "the",
        "target": "little",
        "weight": 18
    }, {
        "source": "i",
        "target": "should",
        "weight": 18
    }, {
        "source": "i",
        "target": "wish",
        "weight": 18
    }, {
        "source": "to",
        "target": "go",
        "weight": 18
    }, {
        "source": "had",
        "target": "been",
        "weight": 18
    }, {
        "source": "it",
        "target": "had",
        "weight": 18
    }, {
        "source": "for",
        "target": "the",
        "weight": 18
    }, {
        "source": "at",
        "target": "last",
        "weight": 18
    }, {
        "source": "said",
        "target": "and",
        "weight": 18
    }, {
        "source": "will",
        "target": "you",
        "weight": 18
    }, {
        "source": "the",
        "target": "first",
        "weight": 17
    }, {
        "source": "alice",
        "target": "was",
        "weight": 17
    }, {
        "source": "to",
        "target": "have",
        "weight": 17
    }, {
        "source": "of",
        "target": "it",
        "weight": 17
    }, {
        "source": "of",
        "target": "her",
        "weight": 17
    }, {
        "source": "of",
        "target": "course",
        "weight": 17
    }, {
        "source": "it",
        "target": "is",
        "weight": 17
    }, {
        "source": "a",
        "target": "great",
        "weight": 17
    }, {
        "source": "would",
        "target": "be",
        "weight": 17
    }, {
        "source": "looked",
        "target": "at",
        "weight": 17
    }, {
        "source": "like",
        "target": "a",
        "weight": 17
    }, {
        "source": "must",
        "target": "be",
        "weight": 17
    }, {
        "source": "you",
        "target": "know'",
        "weight": 17
    }, {
        "source": "was",
        "target": "that",
        "weight": 16
    }, {
        "source": "her",
        "target": "head",
        "weight": 16
    }, {
        "source": "and",
        "target": "a",
        "weight": 16
    }, {
        "source": "for",
        "target": "a",
        "weight": 16
    }, {
        "source": "at",
        "target": "once",
        "weight": 16
    }, {
        "source": "this",
        "target": "time",
        "weight": 16
    }, {
        "source": "they",
        "target": "were",
        "weight": 16
    }, {
        "source": "if",
        "target": "i",
        "weight": 16
    }, {
        "source": "the",
        "target": "time",
        "weight": 15
    }, {
        "source": "the",
        "target": "next",
        "weight": 15
    }, {
        "source": "i",
        "target": "can",
        "weight": 15
    }, {
        "source": "of",
        "target": "them",
        "weight": 15
    }, {
        "source": "she",
        "target": "did",
        "weight": 15
    }, {
        "source": "into",
        "target": "a",
        "weight": 15
    }, {
        "source": "it",
        "target": "would",
        "weight": 15
    }, {
        "source": "a",
        "target": "minute",
        "weight": 15
    }, {
        "source": "as",
        "target": "if",
        "weight": 15
    }, {
        "source": "would",
        "target": "not",
        "weight": 15
    }, {
        "source": "again",
        "target": "and",
        "weight": 15
    }, {
        "source": "sort",
        "target": "of",
        "weight": 15
    }, {
        "source": "two",
        "target": "or",
        "weight": 15
    }, {
        "source": "am",
        "target": "i",
        "weight": 15
    }, {
        "source": "in",
        "target": "it",
        "weight": 14
    }, {
        "source": "the",
        "target": "jury",
        "weight": 14
    }, {
        "source": "i",
        "target": "can't",
        "weight": 14
    }, {
        "source": "and",
        "target": "as",
        "weight": 14
    }, {
        "source": "but",
        "target": "the",
        "weight": 14
    }, {
        "source": "it",
        "target": "to",
        "weight": 14
    }, {
        "source": "a",
        "target": "good",
        "weight": 14
    }, {
        "source": "be",
        "target": "a",
        "weight": 14
    }, {
        "source": "just",
        "target": "as",
        "weight": 14
    }, {
        "source": "in",
        "target": "that",
        "weight": 13
    }, {
        "source": "the",
        "target": "whole",
        "weight": 13
    }, {
        "source": "the",
        "target": "dodo",
        "weight": 13
    }, {
        "source": "the",
        "target": "cook",
        "weight": 13
    }, {
        "source": "the",
        "target": "court",
        "weight": 13
    }, {
        "source": "i",
        "target": "must",
        "weight": 13
    }, {
        "source": "i",
        "target": "know",
        "weight": 13
    }, {
        "source": "to",
        "target": "find",
        "weight": 13
    }, {
        "source": "and",
        "target": "began",
        "weight": 13
    }, {
        "source": "she",
        "target": "found",
        "weight": 13
    }, {
        "source": "she",
        "target": "began",
        "weight": 13
    }, {
        "source": "she",
        "target": "felt",
        "weight": 13
    }, {
        "source": "what",
        "target": "a",
        "weight": 13
    }, {
        "source": "a",
        "target": "long",
        "weight": 13
    }, {
        "source": "as",
        "target": "he",
        "weight": 13
    }, {
        "source": "like",
        "target": "the",
        "weight": 13
    }, {
        "source": "about",
        "target": "it",
        "weight": 13
    }, {
        "source": "they",
        "target": "all",
        "weight": 13
    }, {
        "source": "back",
        "target": "to",
        "weight": 13
    }, {
        "source": "he",
        "target": "said",
        "weight": 13
    }, {
        "source": "the",
        "target": "way",
        "weight": 12
    }, {
        "source": "the",
        "target": "pigeon",
        "weight": 12
    }, {
        "source": "i",
        "target": "never",
        "weight": 12
    }, {
        "source": "down",
        "target": "and",
        "weight": 12
    }, {
        "source": "alice",
        "target": "as",
        "weight": 12
    }, {
        "source": "was",
        "target": "not",
        "weight": 12
    }, {
        "source": "had",
        "target": "to",
        "weight": 12
    }, {
        "source": "but",
        "target": "i",
        "weight": 12
    }, {
        "source": "as",
        "target": "soon",
        "weight": 12
    }, {
        "source": "for",
        "target": "some",
        "weight": 12
    }, {
        "source": "with",
        "target": "one",
        "weight": 12
    }, {
        "source": "that",
        "target": "the",
        "weight": 12
    }, {
        "source": "ought",
        "target": "to",
        "weight": 12
    }, {
        "source": "going",
        "target": "to",
        "weight": 12
    }, {
        "source": "you",
        "target": "see",
        "weight": 12
    }, {
        "source": "you",
        "target": "to",
        "weight": 12
    }, {
        "source": "tell",
        "target": "you",
        "weight": 12
    }, {
        "source": "minute",
        "target": "or",
        "weight": 12
    }, {
        "source": "baby",
        "target": "the",
        "weight": 12
    }, {
        "source": "the",
        "target": "right",
        "weight": 11
    }, {
        "source": "the",
        "target": "end",
        "weight": 11
    }, {
        "source": "the",
        "target": "house",
        "weight": 11
    }, {
        "source": "alice",
        "target": "had",
        "weight": 11
    }, {
        "source": "alice",
        "target": "could",
        "weight": 11
    }, {
        "source": "was",
        "target": "going",
        "weight": 11
    }, {
        "source": "was",
        "target": "i",
        "weight": 11
    }, {
        "source": "and",
        "target": "looked",
        "weight": 11
    }, {
        "source": "and",
        "target": "went",
        "weight": 11
    }, {
        "source": "and",
        "target": "he",
        "weight": 11
    }, {
        "source": "she",
        "target": "heard",
        "weight": 11
    }, {
        "source": "had",
        "target": "never",
        "weight": 11
    }, {
        "source": "what",
        "target": "i",
        "weight": 11
    }, {
        "source": "is",
        "target": "the",
        "weight": 11
    }, {
        "source": "for",
        "target": "it",
        "weight": 11
    }, {
        "source": "when",
        "target": "the",
        "weight": 11
    }, {
        "source": "when",
        "target": "i",
        "weight": 11
    }, {
        "source": "did",
        "target": "alice",
        "weight": 11
    }, {
        "source": "have",
        "target": "you",
        "weight": 11
    }, {
        "source": "at",
        "target": "her",
        "weight": 11
    }, {
        "source": "all",
        "target": "and",
        "weight": 11
    }, {
        "source": "like",
        "target": "to",
        "weight": 11
    }, {
        "source": "about",
        "target": "her",
        "weight": 11
    }, {
        "source": "if",
        "target": "it",
        "weight": 11
    }, {
        "source": "come",
        "target": "to",
        "weight": 11
    }, {
        "source": "end",
        "target": "of",
        "weight": 11
    }, {
        "source": "know",
        "target": "what",
        "weight": 11
    }, {
        "source": "poor",
        "target": "alice",
        "weight": 11
    }, {
        "source": "used",
        "target": "to",
        "weight": 11
    }, {
        "source": "last",
        "target": "the",
        "weight": 11
    }, {
        "source": "in",
        "target": "an",
        "weight": 10
    }, {
        "source": "the",
        "target": "air",
        "weight": 10
    }, {
        "source": "the",
        "target": "words",
        "weight": 10
    }, {
        "source": "the",
        "target": "moment",
        "weight": 10
    }, {
        "source": "the",
        "target": "knave",
        "weight": 10
    }, {
        "source": "i",
        "target": "wonder",
        "weight": 10
    }, {
        "source": "alice",
        "target": "replied",
        "weight": 10
    }, {
        "source": "was",
        "target": "very",
        "weight": 10
    }, {
        "source": "to",
        "target": "make",
        "weight": 10
    }, {
        "source": "of",
        "target": "this",
        "weight": 10
    }, {
        "source": "her",
        "target": "and",
        "weight": 10
    }, {
        "source": "on",
        "target": "it",
        "weight": 10
    }, {
        "source": "and",
        "target": "now",
        "weight": 10
    }, {
        "source": "and",
        "target": "they",
        "weight": 10
    }, {
        "source": "had",
        "target": "not",
        "weight": 10
    }, {
        "source": "had",
        "target": "a",
        "weight": 10
    }, {
        "source": "is",
        "target": "that",
        "weight": 10
    }, {
        "source": "a",
        "target": "low",
        "weight": 10
    }, {
        "source": "for",
        "target": "she",
        "weight": 10
    }, {
        "source": "did",
        "target": "you",
        "weight": 10
    }, {
        "source": "at",
        "target": "this",
        "weight": 10
    }, {
        "source": "at",
        "target": "it",
        "weight": 10
    }, {
        "source": "this",
        "target": "and",
        "weight": 10
    }, {
        "source": "took",
        "target": "the",
        "weight": 10
    }, {
        "source": "if",
        "target": "she",
        "weight": 10
    }, {
        "source": "off",
        "target": "with",
        "weight": 10
    }, {
        "source": "must",
        "target": "have",
        "weight": 10
    }, {
        "source": "near",
        "target": "the",
        "weight": 10
    }, {
        "source": "you",
        "target": "think",
        "weight": 10
    }, {
        "source": "your",
        "target": "majesty'",
        "weight": 10
    }, {
        "source": "while",
        "target": "the",
        "weight": 10
    }, {
        "source": "there's",
        "target": "no",
        "weight": 10
    }, {
        "source": "you'",
        "target": "said",
        "weight": 10
    }, {
        "source": "till",
        "target": "she",
        "weight": 10
    }, {
        "source": "turning",
        "target": "to",
        "weight": 10
    }, {
        "source": "king",
        "target": "and",
        "weight": 10
    }, {
        "source": "in",
        "target": "my",
        "weight": 9
    }, {
        "source": "the",
        "target": "table",
        "weight": 9
    }, {
        "source": "the",
        "target": "garden",
        "weight": 9
    }, {
        "source": "the",
        "target": "poor",
        "weight": 9
    }, {
        "source": "the",
        "target": "dance",
        "weight": 9
    }, {
        "source": "down",
        "target": "the",
        "weight": 9
    }, {
        "source": "alice",
        "target": "began",
        "weight": 9
    }, {
        "source": "alice",
        "target": "in",
        "weight": 9
    }, {
        "source": "was",
        "target": "no",
        "weight": 9
    }, {
        "source": "was",
        "target": "in",
        "weight": 9
    }, {
        "source": "to",
        "target": "speak",
        "weight": 9
    }, {
        "source": "very",
        "target": "much",
        "weight": 9
    }, {
        "source": "of",
        "target": "way",
        "weight": 9
    }, {
        "source": "of",
        "target": "little",
        "weight": 9
    }, {
        "source": "her",
        "target": "with",
        "weight": 9
    }, {
        "source": "and",
        "target": "when",
        "weight": 9
    }, {
        "source": "she",
        "target": "tried",
        "weight": 9
    }, {
        "source": "she",
        "target": "looked",
        "weight": 9
    }, {
        "source": "no",
        "target": "use",
        "weight": 9
    }, {
        "source": "thought",
        "target": "it",
        "weight": 9
    }, {
        "source": "as",
        "target": "i",
        "weight": 9
    }, {
        "source": "when",
        "target": "they",
        "weight": 9
    }, {
        "source": "with",
        "target": "his",
        "weight": 9
    }, {
        "source": "there",
        "target": "were",
        "weight": 9
    }, {
        "source": "at",
        "target": "first",
        "weight": 9
    }, {
        "source": "this",
        "target": "was",
        "weight": 9
    }, {
        "source": "then",
        "target": "the",
        "weight": 9
    }, {
        "source": "after",
        "target": "a",
        "weight": 9
    }, {
        "source": "not",
        "target": "a",
        "weight": 9
    }, {
        "source": "tried",
        "target": "to",
        "weight": 9
    }, {
        "source": "they",
        "target": "had",
        "weight": 9
    }, {
        "source": "from",
        "target": "the",
        "weight": 9
    }, {
        "source": "got",
        "target": "to",
        "weight": 9
    }, {
        "source": "my",
        "target": "dear",
        "weight": 9
    }, {
        "source": "i'm",
        "target": "not",
        "weight": 9
    }, {
        "source": "go",
        "target": "on",
        "weight": 9
    }, {
        "source": "poor",
        "target": "little",
        "weight": 9
    }, {
        "source": "who",
        "target": "was",
        "weight": 9
    }, {
        "source": "sat",
        "target": "down",
        "weight": 9
    }, {
        "source": "set",
        "target": "to",
        "weight": 9
    }, {
        "source": "join",
        "target": "the",
        "weight": 9
    }, {
        "source": "the",
        "target": "top",
        "weight": 8
    }, {
        "source": "the",
        "target": "pool",
        "weight": 8
    }, {
        "source": "the",
        "target": "best",
        "weight": 8
    }, {
        "source": "the",
        "target": "rest",
        "weight": 8
    }, {
        "source": "i",
        "target": "could",
        "weight": 8
    }, {
        "source": "i",
        "target": "suppose",
        "weight": 8
    }, {
        "source": "alice",
        "target": "i",
        "weight": 8
    }, {
        "source": "alice",
        "target": "looked",
        "weight": 8
    }, {
        "source": "was",
        "target": "quite",
        "weight": 8
    }, {
        "source": "to",
        "target": "listen",
        "weight": 8
    }, {
        "source": "of",
        "target": "its",
        "weight": 8
    }, {
        "source": "of",
        "target": "sight",
        "weight": 8
    }, {
        "source": "on",
        "target": "their",
        "weight": 8
    }, {
        "source": "and",
        "target": "i",
        "weight": 8
    }, {
        "source": "and",
        "target": "how",
        "weight": 8
    }, {
        "source": "and",
        "target": "in",
        "weight": 8
    }, {
        "source": "she",
        "target": "ran",
        "weight": 8
    }, {
        "source": "she",
        "target": "came",
        "weight": 8
    }, {
        "source": "she",
        "target": "got",
        "weight": 8
    }, {
        "source": "it",
        "target": "might",
        "weight": 8
    }, {
        "source": "it",
        "target": "then",
        "weight": 8
    }, {
        "source": "what",
        "target": "is",
        "weight": 8
    }, {
        "source": "what",
        "target": "it",
        "weight": 8
    }, {
        "source": "thought",
        "target": "and",
        "weight": 8
    }, {
        "source": "so",
        "target": "much",
        "weight": 8
    }, {
        "source": "so",
        "target": "they",
        "weight": 8
    }, {
        "source": "as",
        "target": "much",
        "weight": 8
    }, {
        "source": "for",
        "target": "her",
        "weight": 8
    }, {
        "source": "would",
        "target": "you",
        "weight": 8
    }, {
        "source": "that",
        "target": "they",
        "weight": 8
    }, {
        "source": "that",
        "target": "you",
        "weight": 8
    }, {
        "source": "have",
        "target": "been",
        "weight": 8
    }, {
        "source": "at",
        "target": "any",
        "weight": 8
    }, {
        "source": "time",
        "target": "to",
        "weight": 8
    }, {
        "source": "then",
        "target": "she",
        "weight": 8
    }, {
        "source": "before",
        "target": "she",
        "weight": 8
    }, {
        "source": "some",
        "target": "of",
        "weight": 8
    }, {
        "source": "about",
        "target": "the",
        "weight": 8
    }, {
        "source": "about",
        "target": "in",
        "weight": 8
    }, {
        "source": "look",
        "target": "at",
        "weight": 8
    }, {
        "source": "were",
        "target": "all",
        "weight": 8
    }, {
        "source": "put",
        "target": "it",
        "weight": 8
    }, {
        "source": "which",
        "target": "was",
        "weight": 8
    }, {
        "source": "said",
        "target": "in",
        "weight": 8
    }, {
        "source": "let",
        "target": "me",
        "weight": 8
    }, {
        "source": "you",
        "target": "can",
        "weight": 8
    }, {
        "source": "that's",
        "target": "the",
        "weight": 8
    }, {
        "source": "began",
        "target": "to",
        "weight": 8
    }, {
        "source": "began",
        "target": "in",
        "weight": 8
    }, {
        "source": "through",
        "target": "the",
        "weight": 8
    }, {
        "source": "among",
        "target": "the",
        "weight": 8
    }, {
        "source": "them",
        "target": "and",
        "weight": 8
    }, {
        "source": "it's",
        "target": "a",
        "weight": 8
    }, {
        "source": "round",
        "target": "the",
        "weight": 8
    }, {
        "source": "trying",
        "target": "to",
        "weight": 8
    }, {
        "source": "who",
        "target": "had",
        "weight": 8
    }, {
        "source": "cried",
        "target": "the",
        "weight": 8
    }, {
        "source": "don't",
        "target": "know",
        "weight": 8
    }, {
        "source": "beautiful",
        "target": "soup",
        "weight": 8
    }, {
        "source": "king",
        "target": "said",
        "weight": 8
    }, {
        "source": "gryphon",
        "target": "and",
        "weight": 8
    }, {
        "source": "in",
        "target": "another",
        "weight": 7
    }, {
        "source": "the",
        "target": "distance",
        "weight": 7
    }, {
        "source": "the",
        "target": "reason",
        "weight": 7
    }, {
        "source": "the",
        "target": "footman",
        "weight": 7
    }, {
        "source": "the",
        "target": "three",
        "weight": 7
    }, {
        "source": "the",
        "target": "queen's",
        "weight": 7
    }, {
        "source": "the",
        "target": "game",
        "weight": 7
    }, {
        "source": "i",
        "target": "have",
        "weight": 7
    }, {
        "source": "i",
        "target": "hadn't",
        "weight": 7
    }, {
        "source": "down",
        "target": "on",
        "weight": 7
    }, {
        "source": "was",
        "target": "so",
        "weight": 7
    }, {
        "source": "beginning",
        "target": "to",
        "weight": 7
    }, {
        "source": "to",
        "target": "think",
        "weight": 7
    }, {
        "source": "to",
        "target": "ask",
        "weight": 7
    }, {
        "source": "to",
        "target": "work",
        "weight": 7
    }, {
        "source": "to",
        "target": "a",
        "weight": 7
    }, {
        "source": "to",
        "target": "them",
        "weight": 7
    }, {
        "source": "to",
        "target": "me",
        "weight": 7
    }, {
        "source": "to",
        "target": "begin",
        "weight": 7
    }, {
        "source": "very",
        "target": "soon",
        "weight": 7
    }, {
        "source": "of",
        "target": "that",
        "weight": 7
    }, {
        "source": "of",
        "target": "his",
        "weight": 7
    }, {
        "source": "of",
        "target": "hearts",
        "weight": 7
    }, {
        "source": "by",
        "target": "this",
        "weight": 7
    }, {
        "source": "her",
        "target": "sister",
        "weight": 7
    }, {
        "source": "her",
        "target": "face",
        "weight": 7
    }, {
        "source": "on",
        "target": "a",
        "weight": 7
    }, {
        "source": "and",
        "target": "had",
        "weight": 7
    }, {
        "source": "and",
        "target": "round",
        "weight": 7
    }, {
        "source": "and",
        "target": "that",
        "weight": 7
    }, {
        "source": "and",
        "target": "so",
        "weight": 7
    }, {
        "source": "and",
        "target": "queen",
        "weight": 7
    }, {
        "source": "she",
        "target": "would",
        "weight": 7
    }, {
        "source": "she",
        "target": "knew",
        "weight": 7
    }, {
        "source": "it",
        "target": "must",
        "weight": 7
    }, {
        "source": "it",
        "target": "doesn't",
        "weight": 7
    }, {
        "source": "what",
        "target": "was",
        "weight": 7
    }, {
        "source": "what",
        "target": "are",
        "weight": 7
    }, {
        "source": "what",
        "target": "you",
        "weight": 7
    }, {
        "source": "a",
        "target": "moment",
        "weight": 7
    }, {
        "source": "a",
        "target": "thing",
        "weight": 7
    }, {
        "source": "so",
        "target": "that",
        "weight": 7
    }, {
        "source": "as",
        "target": "herself",
        "weight": 7
    }, {
        "source": "as",
        "target": "they",
        "weight": 7
    }, {
        "source": "as",
        "target": "a",
        "weight": 7
    }, {
        "source": "be",
        "target": "no",
        "weight": 7
    }, {
        "source": "up",
        "target": "to",
        "weight": 7
    }, {
        "source": "up",
        "target": "into",
        "weight": 7
    }, {
        "source": "with",
        "target": "its",
        "weight": 7
    }, {
        "source": "that",
        "target": "alice",
        "weight": 7
    }, {
        "source": "out",
        "target": "the",
        "weight": 7
    }, {
        "source": "over",
        "target": "all",
        "weight": 7
    }, {
        "source": "at",
        "target": "alice",
        "weight": 7
    }, {
        "source": "all",
        "target": "round",
        "weight": 7
    }, {
        "source": "quite",
        "target": "a",
        "weight": 7
    }, {
        "source": "see",
        "target": "what",
        "weight": 7
    }, {
        "source": "under",
        "target": "the",
        "weight": 7
    }, {
        "source": "went",
        "target": "alice",
        "weight": 7
    }, {
        "source": "went",
        "target": "to",
        "weight": 7
    }, {
        "source": "like",
        "target": "that'",
        "weight": 7
    }, {
        "source": "not",
        "target": "like",
        "weight": 7
    }, {
        "source": "herself",
        "target": "in",
        "weight": 7
    }, {
        "source": "wonder",
        "target": "what",
        "weight": 7
    }, {
        "source": "make",
        "target": "out",
        "weight": 7
    }, {
        "source": "here",
        "target": "and",
        "weight": 7
    }, {
        "source": "upon",
        "target": "a",
        "weight": 7
    }, {
        "source": "off",
        "target": "the",
        "weight": 7
    }, {
        "source": "top",
        "target": "of",
        "weight": 7
    }, {
        "source": "you",
        "target": "might",
        "weight": 7
    }, {
        "source": "you",
        "target": "don't",
        "weight": 7
    }, {
        "source": "good",
        "target": "deal",
        "weight": 7
    }, {
        "source": "got",
        "target": "up",
        "weight": 7
    }, {
        "source": "seem",
        "target": "to",
        "weight": 7
    }, {
        "source": "i'm",
        "target": "sure",
        "weight": 7
    }, {
        "source": "saying",
        "target": "to",
        "weight": 7
    }, {
        "source": "hand",
        "target": "and",
        "weight": 7
    }, {
        "source": "long",
        "target": "as",
        "weight": 7
    }, {
        "source": "any",
        "target": "rate",
        "weight": 7
    }, {
        "source": "cried",
        "target": "alice",
        "weight": 7
    }, {
        "source": "that'",
        "target": "said",
        "weight": 7
    }, {
        "source": "gloves",
        "target": "and",
        "weight": 7
    }, {
        "source": "fan",
        "target": "and",
        "weight": 7
    }, {
        "source": "he",
        "target": "was",
        "weight": 7
    }, {
        "source": "tone",
        "target": "of",
        "weight": 7
    }, {
        "source": "indeed'",
        "target": "said",
        "weight": 7
    }, {
        "source": "called",
        "target": "out",
        "weight": 7
    }, {
        "source": "looking",
        "target": "at",
        "weight": 7
    }, {
        "source": "added",
        "target": "the",
        "weight": 7
    }, {
        "source": "in",
        "target": "at",
        "weight": 6
    }, {
        "source": "the",
        "target": "world",
        "weight": 6
    }, {
        "source": "the",
        "target": "name",
        "weight": 6
    }, {
        "source": "the",
        "target": "roof",
        "weight": 6
    }, {
        "source": "the",
        "target": "middle",
        "weight": 6
    }, {
        "source": "the",
        "target": "fan",
        "weight": 6
    }, {
        "source": "the",
        "target": "great",
        "weight": 6
    }, {
        "source": "the",
        "target": "sea",
        "weight": 6
    }, {
        "source": "the",
        "target": "lory",
        "weight": 6
    }, {
        "source": "the",
        "target": "trees",
        "weight": 6
    }, {
        "source": "the",
        "target": "soldiers",
        "weight": 6
    }, {
        "source": "the",
        "target": "executioner",
        "weight": 6
    }, {
        "source": "the",
        "target": "moral",
        "weight": 6
    }, {
        "source": "i",
        "target": "only",
        "weight": 6
    }, {
        "source": "i",
        "target": "do",
        "weight": 6
    }, {
        "source": "i",
        "target": "beg",
        "weight": 6
    }, {
        "source": "alice",
        "target": "a",
        "weight": 6
    }, {
        "source": "alice",
        "target": "very",
        "weight": 6
    }, {
        "source": "alice",
        "target": "who",
        "weight": 6
    }, {
        "source": "was",
        "target": "just",
        "weight": 6
    }, {
        "source": "was",
        "target": "now",
        "weight": 6
    }, {
        "source": "was",
        "target": "looking",
        "weight": 6
    }, {
        "source": "was",
        "target": "sitting",
        "weight": 6
    }, {
        "source": "to",
        "target": "look",
        "weight": 6
    }, {
        "source": "to",
        "target": "change",
        "weight": 6
    }, {
        "source": "to",
        "target": "tell",
        "weight": 6
    }, {
        "source": "to",
        "target": "grow",
        "weight": 6
    }, {
        "source": "of",
        "target": "course'",
        "weight": 6
    }, {
        "source": "sitting",
        "target": "on",
        "weight": 6
    }, {
        "source": "her",
        "target": "that",
        "weight": 6
    }, {
        "source": "her",
        "target": "hand",
        "weight": 6
    }, {
        "source": "her",
        "target": "hands",
        "weight": 6
    }, {
        "source": "on",
        "target": "going",
        "weight": 6
    }, {
        "source": "on",
        "target": "in",
        "weight": 6
    }, {
        "source": "on",
        "target": "one",
        "weight": 6
    }, {
        "source": "on",
        "target": "her",
        "weight": 6
    }, {
        "source": "and",
        "target": "to",
        "weight": 6
    }, {
        "source": "and",
        "target": "there",
        "weight": 6
    }, {
        "source": "and",
        "target": "that's",
        "weight": 6
    }, {
        "source": "and",
        "target": "found",
        "weight": 6
    }, {
        "source": "and",
        "target": "very",
        "weight": 6
    }, {
        "source": "and",
        "target": "on",
        "weight": 6
    }, {
        "source": "she",
        "target": "might",
        "weight": 6
    }, {
        "source": "but",
        "target": "they",
        "weight": 6
    }, {
        "source": "but",
        "target": "alice",
        "weight": 6
    }, {
        "source": "it",
        "target": "so",
        "weight": 6
    }, {
        "source": "it",
        "target": "when",
        "weight": 6
    }, {
        "source": "it",
        "target": "a",
        "weight": 6
    }, {
        "source": "it",
        "target": "is'",
        "weight": 6
    }, {
        "source": "it",
        "target": "said",
        "weight": 6
    }, {
        "source": "it",
        "target": "out",
        "weight": 6
    }, {
        "source": "what",
        "target": "to",
        "weight": 6
    }, {
        "source": "is",
        "target": "to",
        "weight": 6
    }, {
        "source": "use",
        "target": "in",
        "weight": 6
    }, {
        "source": "a",
        "target": "curious",
        "weight": 6
    }, {
        "source": "a",
        "target": "tone",
        "weight": 6
    }, {
        "source": "so",
        "target": "very",
        "weight": 6
    }, {
        "source": "so",
        "target": "alice",
        "weight": 6
    }, {
        "source": "as",
        "target": "hard",
        "weight": 6
    }, {
        "source": "as",
        "target": "you",
        "weight": 6
    }]
}