const hp1_small = {
    "vertices": ["and", "the", "harry", "potter", "page", "philosophers", "stone", "-", "jk", "rowling", "of", "in", "on", "it", "was", "he", "to", "said", "out", "at", "had", "ron", "be", "a", "hagrid", "they", "were", "uncle", "vernon", "there", "professor", "mcgonagall", "his", "into", "going", "get", "from", "been", "as", "through", "are", "you", "door", "them", "hermione", "trying", "seemed", "with", "over", "for", "though", "one", "other", "have", "all", "aunt", "petunia", "do", "bit", "could", "go", "right", "tried", "back", "dursleys", "first", "then", "know", "but", "him", "head", "few", "like", "i", "think", "dont", "see", "that", "by", "eyes", "up", "very", "didnt", "next", "large", "lot", "if", "around", "couldnt", "house", "mirror", "once", "toward", "same", "ground", "way", "course", "looked", "she", "want", "look", "dumbledore", "air", "room", "end", "never", "down", "off", "who", "when", "got", "about", "this", "is", "face", "train", "mr", "dursley", "hogwarts", "full", "floor", "find", "can", "no", "hand", "not", "only", "school", "boy", "dark", "front", "which", "last", "wall", "keep", "across", "suppose", "hat", "forest", "long", "thought", "what", "able", "three", "against", "still", "little", "must", "come", "how", "hadnt", "dudley", "would", "left", "will", "table", "rest", "say", "so", "just", "looking", "cloak", "asked", "whole", "hall", "library", "tell", "stop", "here", "pulled", "did", "wanted", "wasnt", "hundred", "moment", "corridor", "take", "me", "felt", "feet", "common", "turned", "behind", "sort", "crabbe", "best", "great", "time", "small", "found", "wand", "years", "cant", "mean", "told", "ive", "top", "onto", "managed", "gryffindor", "troll", "try", "much", "almost", "good", "gone", "open", "reached", "took", "each", "granger", "corner", "castle", "quaffle", "mrs", "ask", "talk", "make", "away", "sat", "an", "owl", "yes", "went", "quirrell", "weve", "fred", "snape", "street", "window", "letter", "glass", "snitch", "ollivander", "goyle", "some", "privet", "drive", "now", "knew", "life", "before", "flitwick", "im", "giant", "kitchen", "fire", "bed", "catch", "her", "their", "second", "dragon", "own", "again", "sight", "might", "hed", "its", "enough", "s", "youll", "began", "along", "youve", "nimbus", "two", "walls", "ceiling", "speak", "walked", "saw", "outside", "mind", "mother", "broom", "stared"],
    "edges": [{
        "source": "and",
        "target": "the",
        "weight": 428
    }, {
        "source": "harry",
        "target": "potter",
        "weight": 377
    }, {
        "source": "page",
        "target": "harry",
        "weight": 355
    }, {
        "source": "potter",
        "target": "and",
        "weight": 348
    }, {
        "source": "the",
        "target": "philosophers",
        "weight": 347
    }, {
        "source": "philosophers",
        "target": "stone",
        "weight": 347
    }, {
        "source": "stone",
        "target": "-",
        "weight": 336
    }, {
        "source": "-",
        "target": "jk",
        "weight": 336
    }, {
        "source": "jk",
        "target": "rowling",
        "weight": 336
    }, {
        "source": "of",
        "target": "the",
        "weight": 284
    }, {
        "source": "in",
        "target": "the",
        "weight": 269
    }, {
        "source": "on",
        "target": "the",
        "weight": 217
    }, {
        "source": "it",
        "target": "was",
        "weight": 211
    }, {
        "source": "he",
        "target": "was",
        "weight": 204
    }, {
        "source": "to",
        "target": "the",
        "weight": 173
    }, {
        "source": "said",
        "target": "harry",
        "weight": 153
    }, {
        "source": "out",
        "target": "of",
        "weight": 146
    }, {
        "source": "at",
        "target": "the",
        "weight": 140
    }, {
        "source": "harry",
        "target": "and",
        "weight": 122
    }, {
        "source": "he",
        "target": "had",
        "weight": 117
    }, {
        "source": "said",
        "target": "ron",
        "weight": 117
    }, {
        "source": "he",
        "target": "said",
        "weight": 113
    }, {
        "source": "to",
        "target": "be",
        "weight": 110
    }, {
        "source": "in",
        "target": "a",
        "weight": 105
    }, {
        "source": "hagrid",
        "target": "said",
        "weight": 105
    }, {
        "source": "was",
        "target": "a",
        "weight": 99
    }, {
        "source": "they",
        "target": "were",
        "weight": 97
    }, {
        "source": "uncle",
        "target": "vernon",
        "weight": 97
    }, {
        "source": "and",
        "target": "ron",
        "weight": 93
    }, {
        "source": "there",
        "target": "was",
        "weight": 88
    }, {
        "source": "professor",
        "target": "mcgonagall",
        "weight": 88
    }, {
        "source": "in",
        "target": "his",
        "weight": 85
    }, {
        "source": "into",
        "target": "the",
        "weight": 85
    }, {
        "source": "going",
        "target": "to",
        "weight": 85
    }, {
        "source": "to",
        "target": "get",
        "weight": 81
    }, {
        "source": "from",
        "target": "the",
        "weight": 79
    }, {
        "source": "had",
        "target": "been",
        "weight": 76
    }, {
        "source": "as",
        "target": "he",
        "weight": 75
    }, {
        "source": "through",
        "target": "the",
        "weight": 74
    }, {
        "source": "are",
        "target": "you",
        "weight": 68
    }, {
        "source": "the",
        "target": "door",
        "weight": 67
    }, {
        "source": "of",
        "target": "them",
        "weight": 64
    }, {
        "source": "and",
        "target": "hermione",
        "weight": 62
    }, {
        "source": "of",
        "target": "his",
        "weight": 62
    }, {
        "source": "harry",
        "target": "had",
        "weight": 60
    }, {
        "source": "trying",
        "target": "to",
        "weight": 60
    }, {
        "source": "and",
        "target": "a",
        "weight": 58
    }, {
        "source": "and",
        "target": "he",
        "weight": 57
    }, {
        "source": "seemed",
        "target": "to",
        "weight": 57
    }, {
        "source": "with",
        "target": "the",
        "weight": 56
    }, {
        "source": "over",
        "target": "the",
        "weight": 56
    }, {
        "source": "with",
        "target": "a",
        "weight": 55
    }, {
        "source": "they",
        "target": "had",
        "weight": 54
    }, {
        "source": "for",
        "target": "the",
        "weight": 54
    }, {
        "source": "as",
        "target": "though",
        "weight": 53
    }, {
        "source": "one",
        "target": "of",
        "weight": 53
    }, {
        "source": "the",
        "target": "other",
        "weight": 52
    }, {
        "source": "to",
        "target": "his",
        "weight": 52
    }, {
        "source": "have",
        "target": "to",
        "weight": 52
    }, {
        "source": "on",
        "target": "his",
        "weight": 52
    }, {
        "source": "at",
        "target": "all",
        "weight": 52
    }, {
        "source": "aunt",
        "target": "petunia",
        "weight": 52
    }, {
        "source": "to",
        "target": "do",
        "weight": 51
    }, {
        "source": "a",
        "target": "bit",
        "weight": 51
    }, {
        "source": "as",
        "target": "they",
        "weight": 51
    }, {
        "source": "could",
        "target": "he",
        "weight": 51
    }, {
        "source": "to",
        "target": "go",
        "weight": 50
    }, {
        "source": "harry",
        "target": "was",
        "weight": 49
    }, {
        "source": "all",
        "target": "right",
        "weight": 49
    }, {
        "source": "tried",
        "target": "to",
        "weight": 49
    }, {
        "source": "back",
        "target": "to",
        "weight": 49
    }, {
        "source": "the",
        "target": "dursleys",
        "weight": 48
    }, {
        "source": "the",
        "target": "first",
        "weight": 48
    }, {
        "source": "the",
        "target": "stone",
        "weight": 48
    }, {
        "source": "and",
        "target": "then",
        "weight": 48
    }, {
        "source": "you",
        "target": "know",
        "weight": 48
    }, {
        "source": "had",
        "target": "a",
        "weight": 48
    }, {
        "source": "but",
        "target": "he",
        "weight": 48
    }, {
        "source": "it",
        "target": "had",
        "weight": 48
    }, {
        "source": "of",
        "target": "a",
        "weight": 47
    }, {
        "source": "to",
        "target": "him",
        "weight": 47
    }, {
        "source": "his",
        "target": "head",
        "weight": 46
    }, {
        "source": "said",
        "target": "hermione",
        "weight": 46
    }, {
        "source": "a",
        "target": "few",
        "weight": 45
    }, {
        "source": "like",
        "target": "a",
        "weight": 45
    }, {
        "source": "all",
        "target": "the",
        "weight": 45
    }, {
        "source": "i",
        "target": "think",
        "weight": 45
    }, {
        "source": "you",
        "target": "do",
        "weight": 44
    }, {
        "source": "was",
        "target": "the",
        "weight": 44
    }, {
        "source": "i",
        "target": "dont",
        "weight": 44
    }, {
        "source": "to",
        "target": "see",
        "weight": 43
    }, {
        "source": "was",
        "target": "that",
        "weight": 43
    }, {
        "source": "had",
        "target": "to",
        "weight": 43
    }, {
        "source": "by",
        "target": "the",
        "weight": 43
    }, {
        "source": "it",
        "target": "but",
        "weight": 42
    }, {
        "source": "have",
        "target": "been",
        "weight": 41
    }, {
        "source": "his",
        "target": "eyes",
        "weight": 41
    }, {
        "source": "you",
        "target": "see",
        "weight": 40
    }, {
        "source": "up",
        "target": "the",
        "weight": 40
    }, {
        "source": "into",
        "target": "a",
        "weight": 40
    }, {
        "source": "a",
        "target": "very",
        "weight": 39
    }, {
        "source": "he",
        "target": "didnt",
        "weight": 39
    }, {
        "source": "up",
        "target": "to",
        "weight": 39
    }, {
        "source": "at",
        "target": "him",
        "weight": 39
    }, {
        "source": "the",
        "target": "next",
        "weight": 38
    }, {
        "source": "and",
        "target": "up",
        "weight": 38
    }, {
        "source": "a",
        "target": "large",
        "weight": 38
    }, {
        "source": "a",
        "target": "lot",
        "weight": 38
    }, {
        "source": "if",
        "target": "you",
        "weight": 38
    }, {
        "source": "harry",
        "target": "to",
        "weight": 38
    }, {
        "source": "for",
        "target": "a",
        "weight": 38
    }, {
        "source": "around",
        "target": "the",
        "weight": 38
    }, {
        "source": "he",
        "target": "couldnt",
        "weight": 37
    }, {
        "source": "harry",
        "target": "but",
        "weight": 37
    }, {
        "source": "said",
        "target": "the",
        "weight": 37
    }, {
        "source": "the",
        "target": "house",
        "weight": 36
    }, {
        "source": "the",
        "target": "mirror",
        "weight": 36
    }, {
        "source": "was",
        "target": "going",
        "weight": 36
    }, {
        "source": "at",
        "target": "once",
        "weight": 36
    }, {
        "source": "toward",
        "target": "the",
        "weight": 36
    }, {
        "source": "the",
        "target": "same",
        "weight": 35
    }, {
        "source": "the",
        "target": "ground",
        "weight": 35
    }, {
        "source": "the",
        "target": "way",
        "weight": 35
    }, {
        "source": "and",
        "target": "it",
        "weight": 35
    }, {
        "source": "of",
        "target": "course",
        "weight": 35
    }, {
        "source": "you",
        "target": "dont",
        "weight": 35
    }, {
        "source": "to",
        "target": "a",
        "weight": 34
    }, {
        "source": "in",
        "target": "it",
        "weight": 34
    }, {
        "source": "he",
        "target": "looked",
        "weight": 34
    }, {
        "source": "she",
        "target": "said",
        "weight": 34
    }, {
        "source": "want",
        "target": "to",
        "weight": 34
    }, {
        "source": "look",
        "target": "at",
        "weight": 34
    }, {
        "source": "said",
        "target": "dumbledore",
        "weight": 34
    }, {
        "source": "i",
        "target": "know",
        "weight": 34
    }, {
        "source": "the",
        "target": "air",
        "weight": 33
    }, {
        "source": "the",
        "target": "room",
        "weight": 33
    }, {
        "source": "the",
        "target": "end",
        "weight": 33
    }, {
        "source": "that",
        "target": "he",
        "weight": 33
    }, {
        "source": "had",
        "target": "never",
        "weight": 33
    }, {
        "source": "as",
        "target": "harry",
        "weight": 33
    }, {
        "source": "but",
        "target": "i",
        "weight": 33
    }, {
        "source": "at",
        "target": "harry",
        "weight": 33
    }, {
        "source": "down",
        "target": "the",
        "weight": 33
    }, {
        "source": "off",
        "target": "the",
        "weight": 33
    }, {
        "source": "who",
        "target": "was",
        "weight": 32
    }, {
        "source": "that",
        "target": "the",
        "weight": 32
    }, {
        "source": "him",
        "target": "and",
        "weight": 32
    }, {
        "source": "when",
        "target": "he",
        "weight": 32
    }, {
        "source": "got",
        "target": "to",
        "weight": 32
    }, {
        "source": "next",
        "target": "to",
        "weight": 32
    }, {
        "source": "as",
        "target": "the",
        "weight": 31
    }, {
        "source": "about",
        "target": "the",
        "weight": 31
    }, {
        "source": "this",
        "target": "is",
        "weight": 31
    }, {
        "source": "his",
        "target": "face",
        "weight": 31
    }, {
        "source": "the",
        "target": "train",
        "weight": 30
    }, {
        "source": "mr",
        "target": "dursley",
        "weight": 30
    }, {
        "source": "but",
        "target": "the",
        "weight": 30
    }, {
        "source": "if",
        "target": "he",
        "weight": 30
    }, {
        "source": "at",
        "target": "hogwarts",
        "weight": 30
    }, {
        "source": "is",
        "target": "it",
        "weight": 30
    }, {
        "source": "full",
        "target": "of",
        "weight": 30
    }, {
        "source": "the",
        "target": "floor",
        "weight": 29
    }, {
        "source": "and",
        "target": "they",
        "weight": 29
    }, {
        "source": "to",
        "target": "find",
        "weight": 29
    }, {
        "source": "you",
        "target": "can",
        "weight": 29
    }, {
        "source": "with",
        "target": "his",
        "weight": 29
    }, {
        "source": "have",
        "target": "a",
        "weight": 29
    }, {
        "source": "she",
        "target": "was",
        "weight": 29
    }, {
        "source": "on",
        "target": "it",
        "weight": 29
    }, {
        "source": "no",
        "target": "one",
        "weight": 29
    }, {
        "source": "this",
        "target": "was",
        "weight": 29
    }, {
        "source": "his",
        "target": "hand",
        "weight": 29
    }, {
        "source": "not",
        "target": "to",
        "weight": 29
    }, {
        "source": "only",
        "target": "the",
        "weight": 29
    }, {
        "source": "school",
        "target": "the",
        "weight": 29
    }, {
        "source": "the",
        "target": "boy",
        "weight": 28
    }, {
        "source": "the",
        "target": "dark",
        "weight": 28
    }, {
        "source": "that",
        "target": "harry",
        "weight": 28
    }, {
        "source": "you",
        "target": "and",
        "weight": 28
    }, {
        "source": "in",
        "target": "front",
        "weight": 28
    }, {
        "source": "which",
        "target": "was",
        "weight": 28
    }, {
        "source": "on",
        "target": "a",
        "weight": 28
    }, {
        "source": "at",
        "target": "last",
        "weight": 28
    }, {
        "source": "have",
        "target": "you",
        "weight": 27
    }, {
        "source": "over",
        "target": "his",
        "weight": 27
    }, {
        "source": "there",
        "target": "were",
        "weight": 27
    }, {
        "source": "i",
        "target": "was",
        "weight": 27
    }, {
        "source": "front",
        "target": "of",
        "weight": 27
    }, {
        "source": "the",
        "target": "wall",
        "weight": 26
    }, {
        "source": "the",
        "target": "back",
        "weight": 26
    }, {
        "source": "to",
        "target": "keep",
        "weight": 26
    }, {
        "source": "it",
        "target": "said",
        "weight": 26
    }, {
        "source": "then",
        "target": "he",
        "weight": 26
    }, {
        "source": "across",
        "target": "the",
        "weight": 26
    }, {
        "source": "i",
        "target": "suppose",
        "weight": 26
    }, {
        "source": "hat",
        "target": "the",
        "weight": 26
    }, {
        "source": "the",
        "target": "forest",
        "weight": 25
    }, {
        "source": "a",
        "target": "long",
        "weight": 25
    }, {
        "source": "he",
        "target": "thought",
        "weight": 25
    }, {
        "source": "it",
        "target": "he",
        "weight": 25
    }, {
        "source": "what",
        "target": "was",
        "weight": 25
    }, {
        "source": "end",
        "target": "of",
        "weight": 25
    }, {
        "source": "able",
        "target": "to",
        "weight": 25
    }, {
        "source": "three",
        "target": "of",
        "weight": 25
    }, {
        "source": "against",
        "target": "the",
        "weight": 25
    }, {
        "source": "of",
        "target": "you",
        "weight": 24
    }, {
        "source": "to",
        "target": "it",
        "weight": 24
    }, {
        "source": "they",
        "target": "could",
        "weight": 24
    }, {
        "source": "you",
        "target": "think",
        "weight": 24
    }, {
        "source": "you",
        "target": "to",
        "weight": 24
    }, {
        "source": "was",
        "target": "still",
        "weight": 24
    }, {
        "source": "a",
        "target": "little",
        "weight": 24
    }, {
        "source": "as",
        "target": "if",
        "weight": 24
    }, {
        "source": "if",
        "target": "i",
        "weight": 24
    }, {
        "source": "out",
        "target": "a",
        "weight": 24
    }, {
        "source": "rowling",
        "target": "the",
        "weight": 24
    }, {
        "source": "must",
        "target": "have",
        "weight": 24
    }, {
        "source": "i",
        "target": "can",
        "weight": 24
    }, {
        "source": "come",
        "target": "to",
        "weight": 24
    }, {
        "source": "how",
        "target": "to",
        "weight": 24
    }, {
        "source": "the",
        "target": "last",
        "weight": 23
    }, {
        "source": "and",
        "target": "said",
        "weight": 23
    }, {
        "source": "to",
        "target": "look",
        "weight": 23
    }, {
        "source": "you",
        "target": "could",
        "weight": 23
    }, {
        "source": "was",
        "target": "no",
        "weight": 23
    }, {
        "source": "he",
        "target": "hadnt",
        "weight": 23
    }, {
        "source": "as",
        "target": "it",
        "weight": 23
    }, {
        "source": "dudley",
        "target": "and",
        "weight": 23
    }, {
        "source": "would",
        "target": "be",
        "weight": 23
    }, {
        "source": "harry",
        "target": "could",
        "weight": 23
    }, {
        "source": "harry",
        "target": "looked",
        "weight": 23
    }, {
        "source": "left",
        "target": "the",
        "weight": 23
    }, {
        "source": "down",
        "target": "and",
        "weight": 23
    }, {
        "source": "will",
        "target": "be",
        "weight": 23
    }, {
        "source": "the",
        "target": "table",
        "weight": 22
    }, {
        "source": "the",
        "target": "rest",
        "weight": 22
    }, {
        "source": "to",
        "target": "say",
        "weight": 22
    }, {
        "source": "they",
        "target": "didnt",
        "weight": 22
    }, {
        "source": "was",
        "target": "so",
        "weight": 22
    }, {
        "source": "had",
        "target": "just",
        "weight": 22
    }, {
        "source": "it",
        "target": "if",
        "weight": 22
    }, {
        "source": "harry",
        "target": "didnt",
        "weight": 22
    }, {
        "source": "up",
        "target": "a",
        "weight": 22
    }, {
        "source": "looking",
        "target": "at",
        "weight": 22
    }, {
        "source": "cloak",
        "target": "the",
        "weight": 22
    }, {
        "source": "know",
        "target": "what",
        "weight": 22
    }, {
        "source": "i",
        "target": "have",
        "weight": 22
    }, {
        "source": "looked",
        "target": "at",
        "weight": 22
    }, {
        "source": "dont",
        "target": "know",
        "weight": 22
    }, {
        "source": "professor",
        "target": "dumbledore",
        "weight": 22
    }, {
        "source": "asked",
        "target": "harry",
        "weight": 22
    }, {
        "source": "the",
        "target": "whole",
        "weight": 21
    }, {
        "source": "the",
        "target": "hall",
        "weight": 21
    }, {
        "source": "the",
        "target": "library",
        "weight": 21
    }, {
        "source": "and",
        "target": "his",
        "weight": 21
    }, {
        "source": "to",
        "target": "tell",
        "weight": 21
    }, {
        "source": "to",
        "target": "stop",
        "weight": 21
    }, {
        "source": "in",
        "target": "here",
        "weight": 21
    }, {
        "source": "he",
        "target": "pulled",
        "weight": 21
    }, {
        "source": "did",
        "target": "you",
        "weight": 21
    }, {
        "source": "wanted",
        "target": "to",
        "weight": 21
    }, {
        "source": "but",
        "target": "they",
        "weight": 21
    }, {
        "source": "it",
        "target": "wasnt",
        "weight": 21
    }, {
        "source": "harry",
        "target": "he",
        "weight": 21
    }, {
        "source": "at",
        "target": "his",
        "weight": 21
    }, {
        "source": "at",
        "target": "them",
        "weight": 21
    }, {
        "source": "though",
        "target": "he",
        "weight": 21
    }, {
        "source": "looked",
        "target": "like",
        "weight": 21
    }, {
        "source": "come",
        "target": "on",
        "weight": 21
    }, {
        "source": "hundred",
        "target": "and",
        "weight": 21
    }, {
        "source": "the",
        "target": "moment",
        "weight": 20
    }, {
        "source": "the",
        "target": "corridor",
        "weight": 20
    }, {
        "source": "and",
        "target": "there",
        "weight": 20
    }, {
        "source": "of",
        "target": "all",
        "weight": 20
    }, {
        "source": "to",
        "target": "take",
        "weight": 20
    }, {
        "source": "to",
        "target": "me",
        "weight": 20
    }, {
        "source": "to",
        "target": "know",
        "weight": 20
    }, {
        "source": "be",
        "target": "able",
        "weight": 20
    }, {
        "source": "was",
        "target": "in",
        "weight": 20
    }, {
        "source": "she",
        "target": "had",
        "weight": 20
    }, {
        "source": "could",
        "target": "see",
        "weight": 20
    }, {
        "source": "harry",
        "target": "thought",
        "weight": 20
    }, {
        "source": "harry",
        "target": "felt",
        "weight": 20
    }, {
        "source": "what",
        "target": "he",
        "weight": 20
    }, {
        "source": "up",
        "target": "in",
        "weight": 20
    }, {
        "source": "up",
        "target": "at",
        "weight": 20
    }, {
        "source": "his",
        "target": "feet",
        "weight": 20
    }, {
        "source": "i",
        "target": "want",
        "weight": 20
    }, {
        "source": "common",
        "target": "room",
        "weight": 20
    }, {
        "source": "turned",
        "target": "to",
        "weight": 20
    }, {
        "source": "behind",
        "target": "him",
        "weight": 20
    }, {
        "source": "is",
        "target": "he",
        "weight": 20
    }, {
        "source": "sort",
        "target": "of",
        "weight": 20
    }, {
        "source": "crabbe",
        "target": "and",
        "weight": 20
    }, {
        "source": "the",
        "target": "best",
        "weight": 19
    }, {
        "source": "the",
        "target": "great",
        "weight": 19
    }, {
        "source": "you",
        "target": "will",
        "weight": 19
    }, {
        "source": "in",
        "target": "time",
        "weight": 19
    }, {
        "source": "didnt",
        "target": "have",
        "weight": 19
    }, {
        "source": "was",
        "target": "very",
        "weight": 19
    }, {
        "source": "a",
        "target": "small",
        "weight": 19
    }, {
        "source": "if",
        "target": "they",
        "weight": 19
    }, {
        "source": "found",
        "target": "out",
        "weight": 19
    }, {
        "source": "him",
        "target": "he",
        "weight": 19
    }, {
        "source": "his",
        "target": "wand",
        "weight": 19
    }, {
        "source": "at",
        "target": "it",
        "weight": 19
    }, {
        "source": "first",
        "target": "years",
        "weight": 19
    }, {
        "source": "looking",
        "target": "for",
        "weight": 19
    }, {
        "source": "i",
        "target": "cant",
        "weight": 19
    }, {
        "source": "i",
        "target": "mean",
        "weight": 19
    }, {
        "source": "told",
        "target": "him",
        "weight": 19
    }, {
        "source": "ive",
        "target": "got",
        "weight": 19
    }, {
        "source": "top",
        "target": "of",
        "weight": 19
    }, {
        "source": "go",
        "target": "on",
        "weight": 19
    }, {
        "source": "onto",
        "target": "the",
        "weight": 19
    }, {
        "source": "managed",
        "target": "to",
        "weight": 19
    }, {
        "source": "the",
        "target": "right",
        "weight": 18
    }, {
        "source": "the",
        "target": "gryffindor",
        "weight": 18
    }, {
        "source": "the",
        "target": "troll",
        "weight": 18
    }, {
        "source": "to",
        "target": "try",
        "weight": 18
    }, {
        "source": "you",
        "target": "said",
        "weight": 18
    }, {
        "source": "much",
        "target": "as",
        "weight": 18
    }, {
        "source": "be",
        "target": "a",
        "weight": 18
    }, {
        "source": "didnt",
        "target": "know",
        "weight": 18
    }, {
        "source": "was",
        "target": "looking",
        "weight": 18
    }, {
        "source": "was",
        "target": "almost",
        "weight": 18
    }, {
        "source": "was",
        "target": "hagrid",
        "weight": 18
    }, {
        "source": "a",
        "target": "great",
        "weight": 18
    }, {
        "source": "a",
        "target": "good",
        "weight": 18
    }, {
        "source": "had",
        "target": "gone",
        "weight": 18
    }, {
        "source": "it",
        "target": "harry",
        "weight": 18
    }, {
        "source": "about",
        "target": "it",
        "weight": 18
    }, {
        "source": "when",
        "target": "the",
        "weight": 18
    }, {
        "source": "when",
        "target": "they",
        "weight": 18
    }, {
        "source": "got",
        "target": "a",
        "weight": 18
    }, {
        "source": "said",
        "target": "professor",
        "weight": 18
    }, {
        "source": "said",
        "target": "i",
        "weight": 18
    }, {
        "source": "looked",
        "target": "as",
        "weight": 18
    }, {
        "source": "off",
        "target": "his",
        "weight": 18
    }, {
        "source": "off",
        "target": "to",
        "weight": 18
    }, {
        "source": "open",
        "target": "the",
        "weight": 18
    }, {
        "source": "reached",
        "target": "the",
        "weight": 18
    }, {
        "source": "took",
        "target": "a",
        "weight": 18
    }, {
        "source": "rest",
        "target": "of",
        "weight": 18
    }, {
        "source": "each",
        "target": "other",
        "weight": 18
    }, {
        "source": "hermione",
        "target": "granger",
        "weight": 18
    }, {
        "source": "hermione",
        "target": "had",
        "weight": 18
    }, {
        "source": "the",
        "target": "corner",
        "weight": 17
    }, {
        "source": "the",
        "target": "front",
        "weight": 17
    }, {
        "source": "the",
        "target": "castle",
        "weight": 17
    }, {
        "source": "the",
        "target": "quaffle",
        "weight": 17
    }, {
        "source": "and",
        "target": "i",
        "weight": 17
    }, {
        "source": "mrs",
        "target": "dursley",
        "weight": 17
    }, {
        "source": "were",
        "target": "going",
        "weight": 17
    }, {
        "source": "to",
        "target": "them",
        "weight": 17
    }, {
        "source": "to",
        "target": "ask",
        "weight": 17
    }, {
        "source": "to",
        "target": "talk",
        "weight": 17
    }, {
        "source": "to",
        "target": "make",
        "weight": 17
    }, {
        "source": "he",
        "target": "turned",
        "weight": 17
    }, {
        "source": "time",
        "target": "to",
        "weight": 17
    }, {
        "source": "on",
        "target": "harry",
        "weight": 17
    }, {
        "source": "it",
        "target": "into",
        "weight": 17
    }, {
        "source": "harry",
        "target": "who",
        "weight": 17
    }, {
        "source": "harry",
        "target": "couldnt",
        "weight": 17
    }, {
        "source": "what",
        "target": "are",
        "weight": 17
    }, {
        "source": "this",
        "target": "time",
        "weight": 17
    }, {
        "source": "away",
        "target": "from",
        "weight": 17
    }, {
        "source": "all",
        "target": "over",
        "weight": 17
    }, {
        "source": "into",
        "target": "his",
        "weight": 17
    }, {
        "source": "back",
        "target": "of",
        "weight": 17
    }, {
        "source": "sat",
        "target": "down",
        "weight": 17
    }, {
        "source": "an",
        "target": "owl",
        "weight": 17
    }, {
        "source": "yes",
        "target": "said",
        "weight": 17
    }, {
        "source": "told",
        "target": "harry",
        "weight": 17
    }, {
        "source": "went",
        "target": "to",
        "weight": 17
    }, {
        "source": "professor",
        "target": "quirrell",
        "weight": 17
    }, {
        "source": "weve",
        "target": "got",
        "weight": 17
    }, {
        "source": "hagrid",
        "target": "had",
        "weight": 17
    }, {
        "source": "fred",
        "target": "and",
        "weight": 17
    }, {
        "source": "ron",
        "target": "harry",
        "weight": 17
    }, {
        "source": "snape",
        "target": "was",
        "weight": 17
    }, {
        "source": "the",
        "target": "street",
        "weight": 16
    }, {
        "source": "the",
        "target": "window",
        "weight": 16
    }, {
        "source": "the",
        "target": "letter",
        "weight": 16
    }, {
        "source": "the",
        "target": "glass",
        "weight": 16
    }, {
        "source": "the",
        "target": "snitch",
        "weight": 16
    }, {
        "source": "mr",
        "target": "ollivander",
        "weight": 16
    }, {
        "source": "and",
        "target": "uncle",
        "weight": 16
    }, {
        "source": "and",
        "target": "looked",
        "weight": 16
    }, {
        "source": "and",
        "target": "goyle",
        "weight": 16
    }, {
        "source": "of",
        "target": "it",
        "weight": 16
    }, {
        "source": "of",
        "target": "him",
        "weight": 16
    }, {
        "source": "of",
        "target": "some",
        "weight": 16
    }, {
        "source": "privet",
        "target": "drive",
        "weight": 16
    }, {
        "source": "were",
        "target": "you",
        "weight": 16
    }, {
        "source": "you",
        "target": "all",
        "weight": 16
    }, {
        "source": "in",
        "target": "there",
        "weight": 16
    }, {
        "source": "was",
        "target": "now",
        "weight": 16
    }, {
        "source": "was",
        "target": "hermione",
        "weight": 16
    }, {
        "source": "a",
        "target": "moment",
        "weight": 16
    }, {
        "source": "he",
        "target": "tried",
        "weight": 16
    }, {
        "source": "he",
        "target": "told",
        "weight": 16
    }, {
        "source": "as",
        "target": "a",
        "weight": 16
    }, {
        "source": "as",
        "target": "long",
        "weight": 16
    }, {
        "source": "so",
        "target": "that",
        "weight": 16
    }, {
        "source": "dudley",
        "target": "had",
        "weight": 16
    }, {
        "source": "rowling",
        "target": "harry",
        "weight": 16
    }, {
        "source": "what",
        "target": "they",
        "weight": 16
    }, {
        "source": "what",
        "target": "i",
        "weight": 16
    }, {
        "source": "knew",
        "target": "he",
        "weight": 16
    }, {
        "source": "him",
        "target": "on",
        "weight": 16
    }, {
        "source": "him",
        "target": "in",
        "weight": 16
    }, {
        "source": "his",
        "target": "life",
        "weight": 16
    }, {
        "source": "them",
        "target": "all",
        "weight": 16
    }, {
        "source": "down",
        "target": "to",
        "weight": 16
    }, {
        "source": "bit",
        "target": "of",
        "weight": 16
    }, {
        "source": "i",
        "target": "thought",
        "weight": 16
    }, {
        "source": "before",
        "target": "he",
        "weight": 16
    }, {
        "source": "behind",
        "target": "the",
        "weight": 16
    }, {
        "source": "professor",
        "target": "flitwick",
        "weight": 16
    }, {
        "source": "im",
        "target": "not",
        "weight": 16
    }, {
        "source": "hagrid",
        "target": "and",
        "weight": 16
    }, {
        "source": "try",
        "target": "and",
        "weight": 16
    }, {
        "source": "the",
        "target": "giant",
        "weight": 15
    }, {
        "source": "the",
        "target": "kitchen",
        "weight": 15
    }, {
        "source": "the",
        "target": "time",
        "weight": 15
    }, {
        "source": "the",
        "target": "fire",
        "weight": 15
    }, {
        "source": "and",
        "target": "in",
        "weight": 15
    }, {
        "source": "and",
        "target": "now",
        "weight": 15
    }, {
        "source": "to",
        "target": "bed",
        "weight": 15
    }, {
        "source": "to",
        "target": "catch",
        "weight": 15
    }, {
        "source": "to",
        "target": "her",
        "weight": 15
    }, {
        "source": "to",
        "target": "their",
        "weight": 15
    }, {
        "source": "that",
        "target": "it",
        "weight": 15
    }, {
        "source": "you",
        "target": "cant",
        "weight": 15
    }, {
        "source": "you",
        "target": "get",
        "weight": 15
    }, {
        "source": "be",
        "target": "in",
        "weight": 15
    }, {
        "source": "a",
        "target": "second",
        "weight": 15
    }, {
        "source": "a",
        "target": "dragon",
        "weight": 15
    }, {
        "source": "he",
        "target": "did",
        "weight": 15
    }, {
        "source": "he",
        "target": "wanted",
        "weight": 15
    }, {
        "source": "their",
        "target": "way",
        "weight": 15
    }, {
        "source": "about",
        "target": "to",
        "weight": 15
    }, {
        "source": "him",
        "target": "a",
        "weight": 15
    }, {
        "source": "him",
        "target": "the",
        "weight": 15
    }, {
        "source": "this",
        "target": "in",
        "weight": 15
    }, {
        "source": "when",
        "target": "harry",
        "weight": 15
    }, {
        "source": "all",
        "target": "about",
        "weight": 15
    }, {
        "source": "his",
        "target": "back",
        "weight": 15
    }, {
        "source": "his",
        "target": "own",
        "weight": 15
    }, {
        "source": "again",
        "target": "and",
        "weight": 15
    }, {
        "source": "sight",
        "target": "of",
        "weight": 15
    }, {
        "source": "back",
        "target": "in",
        "weight": 15
    }, {
        "source": "lot",
        "target": "of",
        "weight": 15
    }, {
        "source": "might",
        "target": "be",
        "weight": 15
    }, {
        "source": "down",
        "target": "at",
        "weight": 15
    }, {
        "source": "hed",
        "target": "never",
        "weight": 15
    }, {
        "source": "i",
        "target": "told",
        "weight": 15
    }, {
        "source": "pulled",
        "target": "out",
        "weight": 15
    }, {
        "source": "its",
        "target": "not",
        "weight": 15
    }, {
        "source": "going",
        "target": "on",
        "weight": 15
    }, {
        "source": "only",
        "target": "one",
        "weight": 15
    }, {
        "source": "enough",
        "target": "to",
        "weight": 15
    }, {
        "source": "is",
        "target": "the",
        "weight": 15
    }, {
        "source": "great",
        "target": "hall",
        "weight": 15
    }, {
        "source": "aunt",
        "target": "and",
        "weight": 15
    }, {
        "source": "hagrid",
        "target": "s",
        "weight": 15
    }, {
        "source": "youll",
        "target": "be",
        "weight": 15
    }, {
        "source": "began",
        "target": "to",
        "weight": 15
    }, {
        "source": "along",
        "target": "the",
        "weight": 15
    }, {
        "source": "youve",
        "target": "got",
        "weight": 15
    }, {
        "source": "nimbus",
        "target": "two",
        "weight": 15
    }, {
        "source": "ron",
        "target": "but",
        "weight": 15
    }, {
        "source": "the",
        "target": "walls",
        "weight": 14
    }, {
        "source": "the",
        "target": "ceiling",
        "weight": 14
    }, {
        "source": "who",
        "target": "had",
        "weight": 14
    }, {
        "source": "to",
        "target": "think",
        "weight": 14
    }, {
        "source": "to",
        "target": "speak",
        "weight": 14
    }, {
        "source": "they",
        "target": "walked",
        "weight": 14
    }, {
        "source": "you",
        "target": "harry",
        "weight": 14
    }, {
        "source": "was",
        "target": "on",
        "weight": 14
    }, {
        "source": "was",
        "target": "and",
        "weight": 14
    }, {
        "source": "was",
        "target": "trying",
        "weight": 14
    }, {
        "source": "he",
        "target": "got",
        "weight": 14
    }, {
        "source": "he",
        "target": "wasnt",
        "weight": 14
    }, {
        "source": "he",
        "target": "saw",
        "weight": 14
    }, {
        "source": "he",
        "target": "felt",
        "weight": 14
    }, {
        "source": "had",
        "target": "the",
        "weight": 14
    }, {
        "source": "as",
        "target": "she",
        "weight": 14
    }, {
        "source": "so",
        "target": "much",
        "weight": 14
    }, {
        "source": "on",
        "target": "top",
        "weight": 14
    }, {
        "source": "it",
        "target": "all",
        "weight": 14
    }, {
        "source": "for",
        "target": "you",
        "weight": 14
    }, {
        "source": "outside",
        "target": "the",
        "weight": 14
    }, {
        "source": "all",
        "target": "they",
        "weight": 14
    }, {
        "source": "his",
        "target": "mind",
        "weight": 14
    }, {
        "source": "his",
        "target": "mother",
        "weight": 14
    }, {
        "source": "his",
        "target": "broom",
        "weight": 14
    }, {
        "source": "first",
        "target": "time",
        "weight": 14
    }, {
        "source": "stared",
        "target": "at",
        "weight": 14
    }]
}