const hp4_small = {
    "vertices": ["and", "the", "of", "harry", "potter", "goblet", "fire", "page", "-", "jk", "rowling", "in", "said", "at", "he", "was", "to", "it", "had", "on", "ron", "out", "into", "be", "hermione", "been", "as", "though", "from", "his", "a", "mr", "weasley", "them", "going", "there", "with", "they", "were", "that", "then", "for", "crouch", "could", "dumbledore", "through", "have", "you", "are", "back", "up", "wand", "get", "seemed", "him", "mrs", "around", "she", "one", "head", "do", "over", "all", "know", "dark", "trying", "want", "eyes", "go", "room", "see", "by", "door", "i", "dont", "looked", "across", "front", "who", "other", "course", "but", "toward", "face", "madame", "maxime", "is", "got", "same", "like", "large", "ground", "first", "very", "will", "sort", "ministry", "george", "think", "me", "when", "professor", "mcgonagall", "few", "if", "bit", "castle", "down", "hagrid", "air", "fred", "right", "didnt", "would", "moody", "just", "about", "did", "saw", "began", "way", "top", "still", "own", "great", "not", "rita", "skeeter", "end", "hogwarts", "this", "only", "feet", "what", "knew", "uncle", "vernon", "table", "crowd", "death", "eaters", "never", "her", "come", "hall", "thought", "supposed", "onto", "so", "can", "moment", "am", "look", "talk", "staring", "triwizard", "find", "world", "cup", "magic", "keep", "make", "last", "tournament", "say", "tell", "tried", "entrance", "take", "wanted", "left", "lake", "couldnt", "im", "no", "against", "time", "now", "side", "again", "which", "away", "rest", "felt", "ludo", "bagman", "some", "looking", "need", "sat", "hand", "inside", "champions", "hands", "able", "next", "water", "once", "magical", "more", "stairs", "second", "small", "diggory", "sirius", "voice", "stared", "raised", "common", "grounds", "lot", "before", "mouth", "than", "ever", "off", "quidditch", "long", "set", "floor", "field", "turned", "under", "along", "aunt", "petunia", "yeah", "their", "kitchen", "window", "told", "enough", "returned", "starting", "dursleys", "school", "egg", "sight", "good", "hear", "night", "ive", "behind", "eye", "pulled", "whole", "stone", "parchment", "an", "asked", "each", "robes", "full", "little", "work", "least", "wasnt", "any", "upon", "might", "has", "yes", "daily", "prophet", "viktor", "krum", "tent", "wearing", "sitting", "heard", "reached", "where", "forest", "class", "started"],
    "edges": [{
        "source": "and",
        "target": "the",
        "weight": 1013
    }, {
        "source": "of",
        "target": "the",
        "weight": 902
    }, {
        "source": "harry",
        "target": "potter",
        "weight": 902
    }, {
        "source": "the",
        "target": "goblet",
        "weight": 863
    }, {
        "source": "of",
        "target": "fire",
        "weight": 846
    }, {
        "source": "goblet",
        "target": "of",
        "weight": 841
    }, {
        "source": "page",
        "target": "harry",
        "weight": 823
    }, {
        "source": "potter",
        "target": "and",
        "weight": 817
    }, {
        "source": "fire",
        "target": "-",
        "weight": 786
    }, {
        "source": "-",
        "target": "jk",
        "weight": 786
    }, {
        "source": "jk",
        "target": "rowling",
        "weight": 786
    }, {
        "source": "in",
        "target": "the",
        "weight": 674
    }, {
        "source": "said",
        "target": "harry",
        "weight": 558
    }, {
        "source": "at",
        "target": "the",
        "weight": 499
    }, {
        "source": "he",
        "target": "was",
        "weight": 473
    }, {
        "source": "to",
        "target": "the",
        "weight": 454
    }, {
        "source": "it",
        "target": "was",
        "weight": 383
    }, {
        "source": "he",
        "target": "had",
        "weight": 379
    }, {
        "source": "on",
        "target": "the",
        "weight": 361
    }, {
        "source": "said",
        "target": "ron",
        "weight": 338
    }, {
        "source": "out",
        "target": "of",
        "weight": 325
    }, {
        "source": "into",
        "target": "the",
        "weight": 320
    }, {
        "source": "he",
        "target": "said",
        "weight": 284
    }, {
        "source": "and",
        "target": "harry",
        "weight": 281
    }, {
        "source": "to",
        "target": "be",
        "weight": 274
    }, {
        "source": "said",
        "target": "hermione",
        "weight": 266
    }, {
        "source": "ron",
        "target": "and",
        "weight": 261
    }, {
        "source": "had",
        "target": "been",
        "weight": 254
    }, {
        "source": "as",
        "target": "though",
        "weight": 243
    }, {
        "source": "from",
        "target": "the",
        "weight": 240
    }, {
        "source": "of",
        "target": "his",
        "weight": 221
    }, {
        "source": "in",
        "target": "a",
        "weight": 214
    }, {
        "source": "as",
        "target": "he",
        "weight": 206
    }, {
        "source": "hermione",
        "target": "and",
        "weight": 206
    }, {
        "source": "mr",
        "target": "weasley",
        "weight": 201
    }, {
        "source": "was",
        "target": "a",
        "weight": 192
    }, {
        "source": "of",
        "target": "them",
        "weight": 185
    }, {
        "source": "going",
        "target": "to",
        "weight": 185
    }, {
        "source": "and",
        "target": "he",
        "weight": 182
    }, {
        "source": "in",
        "target": "his",
        "weight": 182
    }, {
        "source": "there",
        "target": "was",
        "weight": 179
    }, {
        "source": "with",
        "target": "a",
        "weight": 179
    }, {
        "source": "they",
        "target": "were",
        "weight": 173
    }, {
        "source": "that",
        "target": "he",
        "weight": 166
    }, {
        "source": "and",
        "target": "then",
        "weight": 165
    }, {
        "source": "for",
        "target": "a",
        "weight": 164
    }, {
        "source": "mr",
        "target": "crouch",
        "weight": 157
    }, {
        "source": "for",
        "target": "the",
        "weight": 156
    }, {
        "source": "of",
        "target": "a",
        "weight": 150
    }, {
        "source": "harry",
        "target": "had",
        "weight": 146
    }, {
        "source": "he",
        "target": "could",
        "weight": 144
    }, {
        "source": "said",
        "target": "dumbledore",
        "weight": 142
    }, {
        "source": "through",
        "target": "the",
        "weight": 142
    }, {
        "source": "to",
        "target": "have",
        "weight": 141
    }, {
        "source": "with",
        "target": "the",
        "weight": 140
    }, {
        "source": "you",
        "target": "are",
        "weight": 140
    }, {
        "source": "back",
        "target": "to",
        "weight": 139
    }, {
        "source": "up",
        "target": "the",
        "weight": 135
    }, {
        "source": "his",
        "target": "wand",
        "weight": 135
    }, {
        "source": "to",
        "target": "get",
        "weight": 133
    }, {
        "source": "seemed",
        "target": "to",
        "weight": 133
    }, {
        "source": "on",
        "target": "his",
        "weight": 131
    }, {
        "source": "said",
        "target": "mr",
        "weight": 131
    }, {
        "source": "at",
        "target": "him",
        "weight": 127
    }, {
        "source": "mrs",
        "target": "weasley",
        "weight": 127
    }, {
        "source": "they",
        "target": "had",
        "weight": 125
    }, {
        "source": "around",
        "target": "the",
        "weight": 124
    }, {
        "source": "she",
        "target": "was",
        "weight": 124
    }, {
        "source": "one",
        "target": "of",
        "weight": 124
    }, {
        "source": "as",
        "target": "they",
        "weight": 123
    }, {
        "source": "his",
        "target": "head",
        "weight": 123
    }, {
        "source": "to",
        "target": "do",
        "weight": 122
    }, {
        "source": "to",
        "target": "him",
        "weight": 120
    }, {
        "source": "at",
        "target": "harry",
        "weight": 119
    }, {
        "source": "over",
        "target": "the",
        "weight": 118
    }, {
        "source": "all",
        "target": "the",
        "weight": 117
    }, {
        "source": "to",
        "target": "his",
        "weight": 117
    }, {
        "source": "up",
        "target": "to",
        "weight": 117
    }, {
        "source": "you",
        "target": "know",
        "weight": 117
    }, {
        "source": "the",
        "target": "dark",
        "weight": 115
    }, {
        "source": "trying",
        "target": "to",
        "weight": 112
    }, {
        "source": "to",
        "target": "want",
        "weight": 109
    }, {
        "source": "his",
        "target": "eyes",
        "weight": 108
    }, {
        "source": "to",
        "target": "go",
        "weight": 107
    }, {
        "source": "she",
        "target": "said",
        "weight": 107
    }, {
        "source": "the",
        "target": "room",
        "weight": 106
    }, {
        "source": "that",
        "target": "was",
        "weight": 106
    }, {
        "source": "to",
        "target": "see",
        "weight": 105
    }, {
        "source": "by",
        "target": "the",
        "weight": 105
    }, {
        "source": "and",
        "target": "it",
        "weight": 104
    }, {
        "source": "the",
        "target": "door",
        "weight": 102
    }, {
        "source": "as",
        "target": "the",
        "weight": 102
    }, {
        "source": "i",
        "target": "dont",
        "weight": 101
    }, {
        "source": "harry",
        "target": "ron",
        "weight": 98
    }, {
        "source": "he",
        "target": "looked",
        "weight": 98
    }, {
        "source": "across",
        "target": "the",
        "weight": 98
    }, {
        "source": "front",
        "target": "of",
        "weight": 98
    }, {
        "source": "to",
        "target": "harry",
        "weight": 97
    }, {
        "source": "who",
        "target": "had",
        "weight": 97
    }, {
        "source": "i",
        "target": "was",
        "weight": 97
    }, {
        "source": "though",
        "target": "he",
        "weight": 96
    }, {
        "source": "that",
        "target": "the",
        "weight": 96
    }, {
        "source": "the",
        "target": "other",
        "weight": 94
    }, {
        "source": "of",
        "target": "course",
        "weight": 94
    }, {
        "source": "in",
        "target": "front",
        "weight": 94
    }, {
        "source": "but",
        "target": "he",
        "weight": 94
    }, {
        "source": "toward",
        "target": "the",
        "weight": 94
    }, {
        "source": "at",
        "target": "all",
        "weight": 92
    }, {
        "source": "up",
        "target": "at",
        "weight": 91
    }, {
        "source": "his",
        "target": "face",
        "weight": 91
    }, {
        "source": "madame",
        "target": "maxime",
        "weight": 91
    }, {
        "source": "it",
        "target": "is",
        "weight": 90
    }, {
        "source": "and",
        "target": "a",
        "weight": 90
    }, {
        "source": "got",
        "target": "to",
        "weight": 88
    }, {
        "source": "to",
        "target": "you",
        "weight": 87
    }, {
        "source": "the",
        "target": "same",
        "weight": 86
    }, {
        "source": "it",
        "target": "had",
        "weight": 86
    }, {
        "source": "like",
        "target": "a",
        "weight": 86
    }, {
        "source": "up",
        "target": "and",
        "weight": 86
    }, {
        "source": "a",
        "target": "large",
        "weight": 85
    }, {
        "source": "the",
        "target": "ground",
        "weight": 84
    }, {
        "source": "harry",
        "target": "was",
        "weight": 84
    }, {
        "source": "who",
        "target": "was",
        "weight": 84
    }, {
        "source": "you",
        "target": "dont",
        "weight": 84
    }, {
        "source": "the",
        "target": "first",
        "weight": 83
    }, {
        "source": "a",
        "target": "very",
        "weight": 83
    }, {
        "source": "will",
        "target": "be",
        "weight": 83
    }, {
        "source": "sort",
        "target": "of",
        "weight": 83
    }, {
        "source": "the",
        "target": "ministry",
        "weight": 82
    }, {
        "source": "and",
        "target": "george",
        "weight": 82
    }, {
        "source": "i",
        "target": "think",
        "weight": 82
    }, {
        "source": "to",
        "target": "me",
        "weight": 81
    }, {
        "source": "when",
        "target": "he",
        "weight": 81
    }, {
        "source": "you",
        "target": "have",
        "weight": 81
    }, {
        "source": "professor",
        "target": "mcgonagall",
        "weight": 80
    }, {
        "source": "a",
        "target": "few",
        "weight": 79
    }, {
        "source": "harry",
        "target": "could",
        "weight": 79
    }, {
        "source": "if",
        "target": "you",
        "weight": 79
    }, {
        "source": "was",
        "target": "the",
        "weight": 78
    }, {
        "source": "had",
        "target": "to",
        "weight": 77
    }, {
        "source": "a",
        "target": "bit",
        "weight": 77
    }, {
        "source": "the",
        "target": "castle",
        "weight": 76
    }, {
        "source": "down",
        "target": "the",
        "weight": 76
    }, {
        "source": "hagrid",
        "target": "said",
        "weight": 76
    }, {
        "source": "into",
        "target": "a",
        "weight": 75
    }, {
        "source": "then",
        "target": "he",
        "weight": 75
    }, {
        "source": "the",
        "target": "air",
        "weight": 74
    }, {
        "source": "and",
        "target": "fred",
        "weight": 73
    }, {
        "source": "all",
        "target": "right",
        "weight": 73
    }, {
        "source": "down",
        "target": "at",
        "weight": 73
    }, {
        "source": "he",
        "target": "didnt",
        "weight": 73
    }, {
        "source": "it",
        "target": "but",
        "weight": 72
    }, {
        "source": "would",
        "target": "be",
        "weight": 72
    }, {
        "source": "moody",
        "target": "said",
        "weight": 72
    }, {
        "source": "had",
        "target": "just",
        "weight": 71
    }, {
        "source": "she",
        "target": "had",
        "weight": 71
    }, {
        "source": "about",
        "target": "the",
        "weight": 71
    }, {
        "source": "he",
        "target": "did",
        "weight": 71
    }, {
        "source": "harry",
        "target": "saw",
        "weight": 70
    }, {
        "source": "have",
        "target": "been",
        "weight": 70
    }, {
        "source": "began",
        "target": "to",
        "weight": 70
    }, {
        "source": "the",
        "target": "way",
        "weight": 69
    }, {
        "source": "it",
        "target": "to",
        "weight": 69
    }, {
        "source": "that",
        "target": "harry",
        "weight": 69
    }, {
        "source": "as",
        "target": "harry",
        "weight": 69
    }, {
        "source": "him",
        "target": "and",
        "weight": 69
    }, {
        "source": "the",
        "target": "top",
        "weight": 68
    }, {
        "source": "was",
        "target": "still",
        "weight": 68
    }, {
        "source": "his",
        "target": "own",
        "weight": 68
    }, {
        "source": "the",
        "target": "great",
        "weight": 67
    }, {
        "source": "and",
        "target": "i",
        "weight": 67
    }, {
        "source": "with",
        "target": "him",
        "weight": 67
    }, {
        "source": "did",
        "target": "not",
        "weight": 67
    }, {
        "source": "he",
        "target": "is",
        "weight": 67
    }, {
        "source": "you",
        "target": "will",
        "weight": 67
    }, {
        "source": "with",
        "target": "his",
        "weight": 66
    }, {
        "source": "he",
        "target": "would",
        "weight": 66
    }, {
        "source": "rita",
        "target": "skeeter",
        "weight": 66
    }, {
        "source": "the",
        "target": "back",
        "weight": 65
    }, {
        "source": "the",
        "target": "end",
        "weight": 65
    }, {
        "source": "at",
        "target": "hogwarts",
        "weight": 65
    }, {
        "source": "into",
        "target": "his",
        "weight": 65
    }, {
        "source": "did",
        "target": "you",
        "weight": 65
    }, {
        "source": "he",
        "target": "harry",
        "weight": 65
    }, {
        "source": "is",
        "target": "this",
        "weight": 65
    }, {
        "source": "the",
        "target": "only",
        "weight": 64
    }, {
        "source": "said",
        "target": "fred",
        "weight": 64
    }, {
        "source": "i",
        "target": "have",
        "weight": 64
    }, {
        "source": "you",
        "target": "said",
        "weight": 64
    }, {
        "source": "his",
        "target": "feet",
        "weight": 64
    }, {
        "source": "of",
        "target": "all",
        "weight": 63
    }, {
        "source": "had",
        "target": "a",
        "weight": 63
    }, {
        "source": "what",
        "target": "was",
        "weight": 63
    }, {
        "source": "he",
        "target": "knew",
        "weight": 63
    }, {
        "source": "i",
        "target": "know",
        "weight": 63
    }, {
        "source": "do",
        "target": "you",
        "weight": 63
    }, {
        "source": "uncle",
        "target": "vernon",
        "weight": 63
    }, {
        "source": "the",
        "target": "table",
        "weight": 62
    }, {
        "source": "the",
        "target": "crowd",
        "weight": 62
    }, {
        "source": "there",
        "target": "were",
        "weight": 62
    }, {
        "source": "and",
        "target": "his",
        "weight": 62
    }, {
        "source": "was",
        "target": "going",
        "weight": 62
    }, {
        "source": "at",
        "target": "his",
        "weight": 62
    }, {
        "source": "could",
        "target": "see",
        "weight": 62
    }, {
        "source": "death",
        "target": "eaters",
        "weight": 62
    }, {
        "source": "would",
        "target": "have",
        "weight": 62
    }, {
        "source": "had",
        "target": "never",
        "weight": 61
    }, {
        "source": "to",
        "target": "her",
        "weight": 61
    }, {
        "source": "harry",
        "target": "looked",
        "weight": 61
    }, {
        "source": "come",
        "target": "to",
        "weight": 61
    }, {
        "source": "great",
        "target": "hall",
        "weight": 61
    }, {
        "source": "thought",
        "target": "he",
        "weight": 61
    }, {
        "source": "him",
        "target": "he",
        "weight": 61
    }, {
        "source": "you",
        "target": "and",
        "weight": 61
    }, {
        "source": "looked",
        "target": "around",
        "weight": 61
    }, {
        "source": "supposed",
        "target": "to",
        "weight": 61
    }, {
        "source": "onto",
        "target": "the",
        "weight": 61
    }, {
        "source": "and",
        "target": "she",
        "weight": 60
    }, {
        "source": "at",
        "target": "her",
        "weight": 60
    }, {
        "source": "them",
        "target": "to",
        "weight": 60
    }, {
        "source": "of",
        "target": "it",
        "weight": 59
    }, {
        "source": "so",
        "target": "that",
        "weight": 59
    }, {
        "source": "you",
        "target": "can",
        "weight": 59
    }, {
        "source": "on",
        "target": "a",
        "weight": 58
    }, {
        "source": "a",
        "target": "moment",
        "weight": 58
    }, {
        "source": "when",
        "target": "they",
        "weight": 58
    }, {
        "source": "i",
        "target": "am",
        "weight": 58
    }, {
        "source": "look",
        "target": "at",
        "weight": 58
    }, {
        "source": "end",
        "target": "of",
        "weight": 58
    }, {
        "source": "talk",
        "target": "to",
        "weight": 58
    }, {
        "source": "staring",
        "target": "at",
        "weight": 58
    }, {
        "source": "the",
        "target": "hall",
        "weight": 57
    }, {
        "source": "the",
        "target": "triwizard",
        "weight": 57
    }, {
        "source": "to",
        "target": "find",
        "weight": 57
    }, {
        "source": "as",
        "target": "a",
        "weight": 57
    }, {
        "source": "but",
        "target": "harry",
        "weight": 57
    }, {
        "source": "world",
        "target": "cup",
        "weight": 57
    }, {
        "source": "over",
        "target": "his",
        "weight": 56
    }, {
        "source": "said",
        "target": "the",
        "weight": 56
    }, {
        "source": "of",
        "target": "magic",
        "weight": 55
    }, {
        "source": "it",
        "target": "said",
        "weight": 55
    }, {
        "source": "to",
        "target": "keep",
        "weight": 55
    }, {
        "source": "to",
        "target": "make",
        "weight": 55
    }, {
        "source": "out",
        "target": "a",
        "weight": 55
    }, {
        "source": "but",
        "target": "i",
        "weight": 55
    }, {
        "source": "the",
        "target": "last",
        "weight": 54
    }, {
        "source": "the",
        "target": "tournament",
        "weight": 54
    }, {
        "source": "of",
        "target": "him",
        "weight": 54
    }, {
        "source": "and",
        "target": "they",
        "weight": 54
    }, {
        "source": "that",
        "target": "they",
        "weight": 54
    }, {
        "source": "to",
        "target": "say",
        "weight": 54
    }, {
        "source": "to",
        "target": "look",
        "weight": 54
    }, {
        "source": "to",
        "target": "tell",
        "weight": 54
    }, {
        "source": "if",
        "target": "he",
        "weight": 54
    }, {
        "source": "tried",
        "target": "to",
        "weight": 54
    }, {
        "source": "the",
        "target": "entrance",
        "weight": 53
    }, {
        "source": "over",
        "target": "to",
        "weight": 53
    }, {
        "source": "to",
        "target": "take",
        "weight": 53
    }, {
        "source": "rowling",
        "target": "the",
        "weight": 53
    }, {
        "source": "wanted",
        "target": "to",
        "weight": 53
    }, {
        "source": "left",
        "target": "the",
        "weight": 53
    }, {
        "source": "the",
        "target": "lake",
        "weight": 52
    }, {
        "source": "to",
        "target": "know",
        "weight": 52
    }, {
        "source": "you",
        "target": "harry",
        "weight": 52
    }, {
        "source": "see",
        "target": "you",
        "weight": 52
    }, {
        "source": "top",
        "target": "of",
        "weight": 52
    }, {
        "source": "at",
        "target": "it",
        "weight": 51
    }, {
        "source": "he",
        "target": "couldnt",
        "weight": 51
    }, {
        "source": "im",
        "target": "not",
        "weight": 51
    }, {
        "source": "said",
        "target": "no",
        "weight": 51
    }, {
        "source": "but",
        "target": "the",
        "weight": 51
    }, {
        "source": "against",
        "target": "the",
        "weight": 51
    }, {
        "source": "the",
        "target": "time",
        "weight": 50
    }, {
        "source": "around",
        "target": "at",
        "weight": 50
    }, {
        "source": "now",
        "target": "and",
        "weight": 50
    }, {
        "source": "to",
        "target": "a",
        "weight": 50
    }, {
        "source": "do",
        "target": "it",
        "weight": 50
    }, {
        "source": "side",
        "target": "of",
        "weight": 50
    }, {
        "source": "again",
        "target": "and",
        "weight": 50
    }, {
        "source": "which",
        "target": "was",
        "weight": 50
    }, {
        "source": "away",
        "target": "from",
        "weight": 50
    }, {
        "source": "the",
        "target": "moment",
        "weight": 49
    }, {
        "source": "the",
        "target": "rest",
        "weight": 49
    }, {
        "source": "it",
        "target": "harry",
        "weight": 49
    }, {
        "source": "he",
        "target": "felt",
        "weight": 49
    }, {
        "source": "come",
        "target": "on",
        "weight": 49
    }, {
        "source": "ludo",
        "target": "bagman",
        "weight": 49
    }, {
        "source": "the",
        "target": "fire",
        "weight": 48
    }, {
        "source": "some",
        "target": "of",
        "weight": 48
    }, {
        "source": "and",
        "target": "said",
        "weight": 48
    }, {
        "source": "i",
        "target": "can",
        "weight": 48
    }, {
        "source": "you",
        "target": "were",
        "weight": 48
    }, {
        "source": "looking",
        "target": "at",
        "weight": 48
    }, {
        "source": "be",
        "target": "a",
        "weight": 48
    }, {
        "source": "looked",
        "target": "up",
        "weight": 48
    }, {
        "source": "need",
        "target": "to",
        "weight": 48
    }, {
        "source": "sat",
        "target": "down",
        "weight": 48
    }, {
        "source": "it",
        "target": "for",
        "weight": 47
    }, {
        "source": "and",
        "target": "down",
        "weight": 47
    }, {
        "source": "all",
        "target": "you",
        "weight": 47
    }, {
        "source": "when",
        "target": "the",
        "weight": 47
    }, {
        "source": "as",
        "target": "she",
        "weight": 47
    }, {
        "source": "i",
        "target": "had",
        "weight": 47
    }, {
        "source": "his",
        "target": "hand",
        "weight": 47
    }, {
        "source": "inside",
        "target": "the",
        "weight": 47
    }, {
        "source": "rest",
        "target": "of",
        "weight": 47
    }, {
        "source": "the",
        "target": "death",
        "weight": 46
    }, {
        "source": "the",
        "target": "champions",
        "weight": 46
    }, {
        "source": "harry",
        "target": "felt",
        "weight": 46
    }, {
        "source": "thought",
        "target": "harry",
        "weight": 46
    }, {
        "source": "his",
        "target": "hands",
        "weight": 46
    }, {
        "source": "able",
        "target": "to",
        "weight": 46
    }, {
        "source": "know",
        "target": "what",
        "weight": 46
    }, {
        "source": "though",
        "target": "it",
        "weight": 45
    }, {
        "source": "and",
        "target": "saw",
        "weight": 45
    }, {
        "source": "with",
        "target": "her",
        "weight": 45
    }, {
        "source": "not",
        "target": "to",
        "weight": 45
    }, {
        "source": "have",
        "target": "a",
        "weight": 45
    }, {
        "source": "next",
        "target": "to",
        "weight": 45
    }, {
        "source": "got",
        "target": "a",
        "weight": 45
    }, {
        "source": "the",
        "target": "water",
        "weight": 44
    }, {
        "source": "a",
        "target": "great",
        "weight": 44
    }, {
        "source": "was",
        "target": "now",
        "weight": 44
    }, {
        "source": "was",
        "target": "no",
        "weight": 44
    }, {
        "source": "that",
        "target": "it",
        "weight": 44
    }, {
        "source": "at",
        "target": "once",
        "weight": 44
    }, {
        "source": "down",
        "target": "to",
        "weight": 44
    }, {
        "source": "him",
        "target": "for",
        "weight": 44
    }, {
        "source": "dont",
        "target": "know",
        "weight": 44
    }, {
        "source": "entrance",
        "target": "hall",
        "weight": 44
    }, {
        "source": "the",
        "target": "one",
        "weight": 43
    }, {
        "source": "of",
        "target": "magical",
        "weight": 43
    }, {
        "source": "once",
        "target": "more",
        "weight": 43
    }, {
        "source": "what",
        "target": "he",
        "weight": 43
    }, {
        "source": "what",
        "target": "said",
        "weight": 43
    }, {
        "source": "could",
        "target": "have",
        "weight": 43
    }, {
        "source": "he",
        "target": "saw",
        "weight": 43
    }, {
        "source": "back",
        "target": "of",
        "weight": 43
    }, {
        "source": "him",
        "target": "a",
        "weight": 43
    }, {
        "source": "i",
        "target": "will",
        "weight": 43
    }, {
        "source": "looked",
        "target": "as",
        "weight": 43
    }, {
        "source": "the",
        "target": "stairs",
        "weight": 42
    }, {
        "source": "the",
        "target": "second",
        "weight": 42
    }, {
        "source": "of",
        "target": "her",
        "weight": 42
    }, {
        "source": "had",
        "target": "that",
        "weight": 42
    }, {
        "source": "a",
        "target": "small",
        "weight": 42
    }, {
        "source": "mr",
        "target": "diggory",
        "weight": 42
    }, {
        "source": "out",
        "target": "his",
        "weight": 42
    }, {
        "source": "said",
        "target": "sirius",
        "weight": 42
    }, {
        "source": "his",
        "target": "voice",
        "weight": 42
    }, {
        "source": "stared",
        "target": "at",
        "weight": 42
    }, {
        "source": "raised",
        "target": "his",
        "weight": 42
    }, {
        "source": "common",
        "target": "room",
        "weight": 42
    }, {
        "source": "the",
        "target": "grounds",
        "weight": 41
    }, {
        "source": "it",
        "target": "he",
        "weight": 41
    }, {
        "source": "a",
        "target": "lot",
        "weight": 41
    }, {
        "source": "before",
        "target": "he",
        "weight": 41
    }, {
        "source": "at",
        "target": "a",
        "weight": 41
    }, {
        "source": "said",
        "target": "george",
        "weight": 41
    }, {
        "source": "said",
        "target": "bagman",
        "weight": 41
    }, {
        "source": "his",
        "target": "mouth",
        "weight": 41
    }, {
        "source": "than",
        "target": "ever",
        "weight": 41
    }, {
        "source": "off",
        "target": "the",
        "weight": 41
    }, {
        "source": "ron",
        "target": "to",
        "weight": 41
    }, {
        "source": "the",
        "target": "quidditch",
        "weight": 40
    }, {
        "source": "the",
        "target": "world",
        "weight": 40
    }, {
        "source": "a",
        "target": "long",
        "weight": 40
    }, {
        "source": "in",
        "target": "it",
        "weight": 40
    }, {
        "source": "at",
        "target": "them",
        "weight": 40
    }, {
        "source": "back",
        "target": "into",
        "weight": 40
    }, {
        "source": "set",
        "target": "off",
        "weight": 40
    }, {
        "source": "the",
        "target": "floor",
        "weight": 39
    }, {
        "source": "the",
        "target": "field",
        "weight": 39
    }, {
        "source": "was",
        "target": "in",
        "weight": 39
    }, {
        "source": "all",
        "target": "over",
        "weight": 39
    }, {
        "source": "turned",
        "target": "to",
        "weight": 39
    }, {
        "source": "him",
        "target": "the",
        "weight": 39
    }, {
        "source": "under",
        "target": "the",
        "weight": 39
    }, {
        "source": "along",
        "target": "the",
        "weight": 39
    }, {
        "source": "wand",
        "target": "and",
        "weight": 39
    }, {
        "source": "aunt",
        "target": "petunia",
        "weight": 39
    }, {
        "source": "yeah",
        "target": "said",
        "weight": 39
    }, {
        "source": "the",
        "target": "next",
        "weight": 38
    }, {
        "source": "it",
        "target": "would",
        "weight": 38
    }, {
        "source": "on",
        "target": "him",
        "weight": 38
    }, {
        "source": "and",
        "target": "there",
        "weight": 38
    }, {
        "source": "in",
        "target": "their",
        "weight": 38
    }, {
        "source": "as",
        "target": "it",
        "weight": 38
    }, {
        "source": "didnt",
        "target": "i",
        "weight": 38
    }, {
        "source": "then",
        "target": "said",
        "weight": 38
    }, {
        "source": "i",
        "target": "could",
        "weight": 38
    }, {
        "source": "i",
        "target": "thought",
        "weight": 38
    }, {
        "source": "right",
        "target": "said",
        "weight": 38
    }, {
        "source": "bit",
        "target": "of",
        "weight": 38
    }, {
        "source": "the",
        "target": "kitchen",
        "weight": 37
    }, {
        "source": "the",
        "target": "window",
        "weight": 37
    }, {
        "source": "and",
        "target": "was",
        "weight": 37
    }, {
        "source": "around",
        "target": "him",
        "weight": 37
    }, {
        "source": "was",
        "target": "not",
        "weight": 37
    }, {
        "source": "was",
        "target": "looking",
        "weight": 37
    }, {
        "source": "told",
        "target": "you",
        "weight": 37
    }, {
        "source": "said",
        "target": "mrs",
        "weight": 37
    }, {
        "source": "said",
        "target": "professor",
        "weight": 37
    }, {
        "source": "enough",
        "target": "to",
        "weight": 37
    }, {
        "source": "returned",
        "target": "to",
        "weight": 37
    }, {
        "source": "starting",
        "target": "to",
        "weight": 37
    }, {
        "source": "see",
        "target": "the",
        "weight": 37
    }, {
        "source": "the",
        "target": "dursleys",
        "weight": 36
    }, {
        "source": "the",
        "target": "school",
        "weight": 36
    }, {
        "source": "the",
        "target": "egg",
        "weight": 36
    }, {
        "source": "of",
        "target": "sight",
        "weight": 36
    }, {
        "source": "a",
        "target": "good",
        "weight": 36
    }, {
        "source": "and",
        "target": "dumbledore",
        "weight": 36
    }, {
        "source": "to",
        "target": "think",
        "weight": 36
    }, {
        "source": "in",
        "target": "her",
        "weight": 36
    }, {
        "source": "could",
        "target": "hear",
        "weight": 36
    }, {
        "source": "night",
        "target": "the",
        "weight": 36
    }, {
        "source": "ive",
        "target": "got",
        "weight": 36
    }, {
        "source": "him",
        "target": "in",
        "weight": 36
    }, {
        "source": "behind",
        "target": "the",
        "weight": 36
    }, {
        "source": "magical",
        "target": "eye",
        "weight": 36
    }, {
        "source": "pulled",
        "target": "out",
        "weight": 36
    }, {
        "source": "the",
        "target": "whole",
        "weight": 35
    }, {
        "source": "the",
        "target": "stone",
        "weight": 35
    }, {
        "source": "of",
        "target": "their",
        "weight": 35
    }, {
        "source": "of",
        "target": "parchment",
        "weight": 35
    }, {
        "source": "it",
        "target": "into",
        "weight": 35
    }, {
        "source": "from",
        "target": "him",
        "weight": 35
    }, {
        "source": "from",
        "target": "his",
        "weight": 35
    }, {
        "source": "and",
        "target": "began",
        "weight": 35
    }, {
        "source": "in",
        "target": "there",
        "weight": 35
    }, {
        "source": "in",
        "target": "an",
        "weight": 35
    }, {
        "source": "harry",
        "target": "who",
        "weight": 35
    }, {
        "source": "harry",
        "target": "i",
        "weight": 35
    }, {
        "source": "harry",
        "target": "asked",
        "weight": 35
    }, {
        "source": "rowling",
        "target": "harry",
        "weight": 35
    }, {
        "source": "about",
        "target": "to",
        "weight": 35
    }, {
        "source": "he",
        "target": "turned",
        "weight": 35
    }, {
        "source": "said",
        "target": "to",
        "weight": 35
    }, {
        "source": "you",
        "target": "for",
        "weight": 35
    }, {
        "source": "by",
        "target": "a",
        "weight": 35
    }, {
        "source": "each",
        "target": "of",
        "weight": 35
    }, {
        "source": "his",
        "target": "robes",
        "weight": 35
    }, {
        "source": "full",
        "target": "of",
        "weight": 35
    }, {
        "source": "is",
        "target": "a",
        "weight": 35
    }, {
        "source": "quidditch",
        "target": "world",
        "weight": 35
    }, {
        "source": "professor",
        "target": "dumbledore",
        "weight": 35
    }, {
        "source": "triwizard",
        "target": "tournament",
        "weight": 35
    }, {
        "source": "the",
        "target": "cup",
        "weight": 34
    }, {
        "source": "had",
        "target": "not",
        "weight": 34
    }, {
        "source": "had",
        "target": "the",
        "weight": 34
    }, {
        "source": "on",
        "target": "it",
        "weight": 34
    }, {
        "source": "a",
        "target": "little",
        "weight": 34
    }, {
        "source": "and",
        "target": "that",
        "weight": 34
    }, {
        "source": "to",
        "target": "work",
        "weight": 34
    }, {
        "source": "at",
        "target": "least",
        "weight": 34
    }, {
        "source": "they",
        "target": "could",
        "weight": 34
    }, {
        "source": "he",
        "target": "wasnt",
        "weight": 34
    }, {
        "source": "like",
        "target": "the",
        "weight": 34
    }, {
        "source": "him",
        "target": "but",
        "weight": 34
    }, {
        "source": "any",
        "target": "of",
        "weight": 34
    }, {
        "source": "tell",
        "target": "you",
        "weight": 34
    }, {
        "source": "each",
        "target": "other",
        "weight": 34
    }, {
        "source": "upon",
        "target": "the",
        "weight": 34
    }, {
        "source": "might",
        "target": "be",
        "weight": 34
    }, {
        "source": "has",
        "target": "been",
        "weight": 34
    }, {
        "source": "behind",
        "target": "him",
        "weight": 34
    }, {
        "source": "yes",
        "target": "said",
        "weight": 34
    }, {
        "source": "daily",
        "target": "prophet",
        "weight": 34
    }, {
        "source": "viktor",
        "target": "krum",
        "weight": 34
    }, {
        "source": "the",
        "target": "tent",
        "weight": 33
    }, {
        "source": "around",
        "target": "and",
        "weight": 33
    }, {
        "source": "was",
        "target": "wearing",
        "weight": 33
    }, {
        "source": "was",
        "target": "sitting",
        "weight": 33
    }, {
        "source": "were",
        "target": "all",
        "weight": 33
    }, {
        "source": "about",
        "target": "it",
        "weight": 33
    }, {
        "source": "did",
        "target": "it",
        "weight": 33
    }, {
        "source": "out",
        "target": "the",
        "weight": 33
    }, {
        "source": "he",
        "target": "heard",
        "weight": 33
    }, {
        "source": "more",
        "target": "than",
        "weight": 33
    }, {
        "source": "told",
        "target": "him",
        "weight": 33
    }, {
        "source": "i",
        "target": "would",
        "weight": 33
    }, {
        "source": "them",
        "target": "and",
        "weight": 33
    }, {
        "source": "reached",
        "target": "the",
        "weight": 33
    }, {
        "source": "where",
        "target": "he",
        "weight": 33
    }, {
        "source": "think",
        "target": "you",
        "weight": 33
    }, {
        "source": "time",
        "target": "he",
        "weight": 33
    }, {
        "source": "behind",
        "target": "them",
        "weight": 33
    }, {
        "source": "the",
        "target": "forest",
        "weight": 32
    }, {
        "source": "the",
        "target": "class",
        "weight": 32
    }, {
        "source": "that",
        "target": "you",
        "weight": 32
    }, {
        "source": "started",
        "target": "to",
        "weight": 32
    }, {
        "source": "eyes",
        "target": "were",
        "weight": 32
    }, {
        "source": "just",
        "target": "as",
        "weight": 32
    }, {
        "source": "her",
        "target": "and",
        "weight": 32
    }, {
        "source": "like",
        "target": "that",
        "weight": 32
    }, {
        "source": "looking",
        "target": "around",
        "weight": 32
    }, {
        "source": "go",
        "target": "and",
        "weight": 32
    }, {
        "source": "looked",
        "target": "like",
        "weight": 32
    }, {
        "source": "is",
        "target": "not",
        "weight": 32
    }]
}