const hp7_small = {
    "vertices": ["and", "the", "of", "harry", "potter", "deathly", "hallows", "page", "-", "jk", "rowling", "in", "he", "had", "said", "it", "was", "at", "on", "to", "out", "into", "from", "as", "hermione", "ron", "could", "there", "did", "not", "been", "be", "his", "a", "that", "through", "with", "for", "they", "were", "seemed", "them", "have", "i", "think", "room", "him", "wand", "you", "are", "over", "is", "death", "eaters", "going", "door", "do", "little", "eyes", "then", "know", "dont", "she", "dark", "get", "other", "one", "trying", "sword", "by", "like", "who", "knew", "if", "own", "go", "around", "see", "toward", "want", "felt", "floor", "same", "first", "but", "looked", "up", "thought", "air", "mrs", "weasley", "though", "cloak", "few", "back", "her", "head", "when", "ministry", "would", "place", "saw", "me", "front", "all", "right", "got", "tent", "need", "only", "course", "find", "can", "able", "this", "wanted", "asked", "come", "moment", "make", "darkness", "way", "we", "dumbledore", "am", "face", "voice", "once", "off", "now", "never", "onto", "tried", "last", "elder", "each", "feet", "down", "about", "invisibility", "supposed", "ground", "goblin", "what", "eater", "still", "across", "end", "locket", "castle", "small", "hand", "keep", "under", "top", "away", "look", "sight", "will", "just", "mr", "im", "sorry", "boy", "great", "lupin", "against", "upon", "godrics", "hollow", "horcrux", "more", "than", "side", "voldemort", "scar", "bit", "so", "professor", "mcgonagall", "didnt", "take", "again", "table", "where", "kitchen", "might", "began", "cant", "long", "tell", "time", "talk", "two", "window", "their", "my", "lord", "before", "no", "stairs", "hogwarts", "beneath", "order", "night", "snake", "hall", "us", "which", "try", "s", "old", "house", "bill", "say", "after", "any", "close", "isnt", "full", "magic", "here", "must", "wall", "entrance", "turned", "some", "ought", "stone", "rest", "three", "well", "hands", "told", "others", "behind", "how", "inside", "fred", "whole", "elf", "light", "raised", "nothing", "sure", "thank", "snape", "leave", "looking", "unable", "beside", "its", "youve", "luna", "truth", "thing", "mind", "heart", "pulled", "sound", "give", "taken", "part", "gave", "happened", "weve"],
    "edges": [{
        "source": "and",
        "target": "the",
        "weight": 1165
    }, {
        "source": "of",
        "target": "the",
        "weight": 1003
    }, {
        "source": "harry",
        "target": "potter",
        "weight": 925
    }, {
        "source": "the",
        "target": "deathly",
        "weight": 887
    }, {
        "source": "deathly",
        "target": "hallows",
        "weight": 887
    }, {
        "source": "potter",
        "target": "and",
        "weight": 873
    }, {
        "source": "page",
        "target": "harry",
        "weight": 865
    }, {
        "source": "hallows",
        "target": "-",
        "weight": 843
    }, {
        "source": "-",
        "target": "jk",
        "weight": 843
    }, {
        "source": "jk",
        "target": "rowling",
        "weight": 843
    }, {
        "source": "in",
        "target": "the",
        "weight": 674
    }, {
        "source": "he",
        "target": "had",
        "weight": 486
    }, {
        "source": "said",
        "target": "harry",
        "weight": 469
    }, {
        "source": "it",
        "target": "was",
        "weight": 456
    }, {
        "source": "he",
        "target": "was",
        "weight": 453
    }, {
        "source": "at",
        "target": "the",
        "weight": 424
    }, {
        "source": "on",
        "target": "the",
        "weight": 420
    }, {
        "source": "to",
        "target": "the",
        "weight": 412
    }, {
        "source": "out",
        "target": "of",
        "weight": 321
    }, {
        "source": "into",
        "target": "the",
        "weight": 305
    }, {
        "source": "and",
        "target": "harry",
        "weight": 294
    }, {
        "source": "from",
        "target": "the",
        "weight": 285
    }, {
        "source": "and",
        "target": "he",
        "weight": 267
    }, {
        "source": "as",
        "target": "he",
        "weight": 260
    }, {
        "source": "hermione",
        "target": "and",
        "weight": 258
    }, {
        "source": "said",
        "target": "ron",
        "weight": 256
    }, {
        "source": "he",
        "target": "could",
        "weight": 254
    }, {
        "source": "there",
        "target": "was",
        "weight": 254
    }, {
        "source": "did",
        "target": "not",
        "weight": 253
    }, {
        "source": "had",
        "target": "been",
        "weight": 250
    }, {
        "source": "to",
        "target": "be",
        "weight": 249
    }, {
        "source": "ron",
        "target": "and",
        "weight": 245
    }, {
        "source": "said",
        "target": "hermione",
        "weight": 244
    }, {
        "source": "of",
        "target": "his",
        "weight": 232
    }, {
        "source": "was",
        "target": "a",
        "weight": 218
    }, {
        "source": "in",
        "target": "his",
        "weight": 204
    }, {
        "source": "that",
        "target": "he",
        "weight": 204
    }, {
        "source": "through",
        "target": "the",
        "weight": 196
    }, {
        "source": "with",
        "target": "a",
        "weight": 193
    }, {
        "source": "in",
        "target": "a",
        "weight": 183
    }, {
        "source": "for",
        "target": "the",
        "weight": 181
    }, {
        "source": "they",
        "target": "were",
        "weight": 176
    }, {
        "source": "seemed",
        "target": "to",
        "weight": 176
    }, {
        "source": "of",
        "target": "them",
        "weight": 172
    }, {
        "source": "he",
        "target": "said",
        "weight": 170
    }, {
        "source": "have",
        "target": "to",
        "weight": 168
    }, {
        "source": "i",
        "target": "think",
        "weight": 159
    }, {
        "source": "of",
        "target": "a",
        "weight": 158
    }, {
        "source": "with",
        "target": "the",
        "weight": 157
    }, {
        "source": "the",
        "target": "room",
        "weight": 153
    }, {
        "source": "to",
        "target": "him",
        "weight": 153
    }, {
        "source": "could",
        "target": "not",
        "weight": 150
    }, {
        "source": "his",
        "target": "wand",
        "weight": 149
    }, {
        "source": "you",
        "target": "are",
        "weight": 146
    }, {
        "source": "over",
        "target": "the",
        "weight": 145
    }, {
        "source": "it",
        "target": "is",
        "weight": 144
    }, {
        "source": "death",
        "target": "eaters",
        "weight": 143
    }, {
        "source": "they",
        "target": "had",
        "weight": 141
    }, {
        "source": "going",
        "target": "to",
        "weight": 141
    }, {
        "source": "the",
        "target": "door",
        "weight": 138
    }, {
        "source": "to",
        "target": "do",
        "weight": 135
    }, {
        "source": "a",
        "target": "little",
        "weight": 132
    }, {
        "source": "for",
        "target": "a",
        "weight": 131
    }, {
        "source": "his",
        "target": "eyes",
        "weight": 129
    }, {
        "source": "and",
        "target": "then",
        "weight": 128
    }, {
        "source": "he",
        "target": "did",
        "weight": 128
    }, {
        "source": "you",
        "target": "know",
        "weight": 128
    }, {
        "source": "i",
        "target": "dont",
        "weight": 127
    }, {
        "source": "that",
        "target": "the",
        "weight": 126
    }, {
        "source": "to",
        "target": "his",
        "weight": 126
    }, {
        "source": "she",
        "target": "was",
        "weight": 125
    }, {
        "source": "the",
        "target": "dark",
        "weight": 122
    }, {
        "source": "to",
        "target": "get",
        "weight": 121
    }, {
        "source": "and",
        "target": "it",
        "weight": 120
    }, {
        "source": "the",
        "target": "other",
        "weight": 119
    }, {
        "source": "do",
        "target": "you",
        "weight": 119
    }, {
        "source": "as",
        "target": "the",
        "weight": 118
    }, {
        "source": "and",
        "target": "a",
        "weight": 115
    }, {
        "source": "of",
        "target": "one",
        "weight": 114
    }, {
        "source": "harry",
        "target": "had",
        "weight": 114
    }, {
        "source": "trying",
        "target": "to",
        "weight": 113
    }, {
        "source": "the",
        "target": "sword",
        "weight": 110
    }, {
        "source": "that",
        "target": "it",
        "weight": 110
    }, {
        "source": "by",
        "target": "the",
        "weight": 109
    }, {
        "source": "as",
        "target": "they",
        "weight": 109
    }, {
        "source": "have",
        "target": "been",
        "weight": 109
    }, {
        "source": "like",
        "target": "a",
        "weight": 108
    }, {
        "source": "the",
        "target": "death",
        "weight": 106
    }, {
        "source": "it",
        "target": "had",
        "weight": 106
    }, {
        "source": "who",
        "target": "had",
        "weight": 104
    }, {
        "source": "and",
        "target": "his",
        "weight": 103
    }, {
        "source": "he",
        "target": "knew",
        "weight": 103
    }, {
        "source": "that",
        "target": "was",
        "weight": 103
    }, {
        "source": "if",
        "target": "you",
        "weight": 103
    }, {
        "source": "i",
        "target": "was",
        "weight": 102
    }, {
        "source": "his",
        "target": "own",
        "weight": 101
    }, {
        "source": "go",
        "target": "to",
        "weight": 101
    }, {
        "source": "i",
        "target": "know",
        "weight": 100
    }, {
        "source": "around",
        "target": "the",
        "weight": 100
    }, {
        "source": "have",
        "target": "you",
        "weight": 100
    }, {
        "source": "was",
        "target": "the",
        "weight": 98
    }, {
        "source": "to",
        "target": "see",
        "weight": 98
    }, {
        "source": "that",
        "target": "they",
        "weight": 96
    }, {
        "source": "the",
        "target": "wand",
        "weight": 95
    }, {
        "source": "and",
        "target": "i",
        "weight": 95
    }, {
        "source": "toward",
        "target": "the",
        "weight": 95
    }, {
        "source": "want",
        "target": "to",
        "weight": 95
    }, {
        "source": "he",
        "target": "felt",
        "weight": 93
    }, {
        "source": "him",
        "target": "and",
        "weight": 93
    }, {
        "source": "harry",
        "target": "was",
        "weight": 92
    }, {
        "source": "at",
        "target": "him",
        "weight": 91
    }, {
        "source": "as",
        "target": "she",
        "weight": 91
    }, {
        "source": "harry",
        "target": "could",
        "weight": 91
    }, {
        "source": "did",
        "target": "you",
        "weight": 91
    }, {
        "source": "to",
        "target": "you",
        "weight": 91
    }, {
        "source": "floor",
        "target": "the",
        "weight": 91
    }, {
        "source": "the",
        "target": "same",
        "weight": 90
    }, {
        "source": "the",
        "target": "first",
        "weight": 90
    }, {
        "source": "but",
        "target": "he",
        "weight": 90
    }, {
        "source": "she",
        "target": "said",
        "weight": 90
    }, {
        "source": "as",
        "target": "harry",
        "weight": 89
    }, {
        "source": "he",
        "target": "looked",
        "weight": 89
    }, {
        "source": "up",
        "target": "the",
        "weight": 88
    }, {
        "source": "was",
        "target": "not",
        "weight": 87
    }, {
        "source": "thought",
        "target": "he",
        "weight": 87
    }, {
        "source": "the",
        "target": "air",
        "weight": 86
    }, {
        "source": "of",
        "target": "it",
        "weight": 85
    }, {
        "source": "mrs",
        "target": "weasley",
        "weight": 85
    }, {
        "source": "it",
        "target": "but",
        "weight": 84
    }, {
        "source": "harry",
        "target": "but",
        "weight": 84
    }, {
        "source": "as",
        "target": "though",
        "weight": 83
    }, {
        "source": "the",
        "target": "cloak",
        "weight": 82
    }, {
        "source": "a",
        "target": "few",
        "weight": 82
    }, {
        "source": "on",
        "target": "his",
        "weight": 82
    }, {
        "source": "back",
        "target": "to",
        "weight": 82
    }, {
        "source": "had",
        "target": "not",
        "weight": 82
    }, {
        "source": "her",
        "target": "to",
        "weight": 82
    }, {
        "source": "his",
        "target": "head",
        "weight": 81
    }, {
        "source": "but",
        "target": "the",
        "weight": 81
    }, {
        "source": "when",
        "target": "he",
        "weight": 81
    }, {
        "source": "the",
        "target": "ministry",
        "weight": 80
    }, {
        "source": "you",
        "target": "and",
        "weight": 80
    }, {
        "source": "not",
        "target": "to",
        "weight": 80
    }, {
        "source": "would",
        "target": "have",
        "weight": 80
    }, {
        "source": "the",
        "target": "place",
        "weight": 79
    }, {
        "source": "he",
        "target": "saw",
        "weight": 79
    }, {
        "source": "to",
        "target": "me",
        "weight": 79
    }, {
        "source": "to",
        "target": "harry",
        "weight": 79
    }, {
        "source": "front",
        "target": "of",
        "weight": 79
    }, {
        "source": "all",
        "target": "right",
        "weight": 79
    }, {
        "source": "who",
        "target": "was",
        "weight": 78
    }, {
        "source": "him",
        "target": "he",
        "weight": 77
    }, {
        "source": "all",
        "target": "the",
        "weight": 77
    }, {
        "source": "got",
        "target": "to",
        "weight": 77
    }, {
        "source": "the",
        "target": "tent",
        "weight": 76
    }, {
        "source": "he",
        "target": "would",
        "weight": 76
    }, {
        "source": "of",
        "target": "all",
        "weight": 74
    }, {
        "source": "thought",
        "target": "i",
        "weight": 74
    }, {
        "source": "need",
        "target": "to",
        "weight": 74
    }, {
        "source": "the",
        "target": "only",
        "weight": 73
    }, {
        "source": "of",
        "target": "course",
        "weight": 73
    }, {
        "source": "there",
        "target": "were",
        "weight": 73
    }, {
        "source": "to",
        "target": "find",
        "weight": 73
    }, {
        "source": "would",
        "target": "be",
        "weight": 73
    }, {
        "source": "can",
        "target": "you",
        "weight": 73
    }, {
        "source": "able",
        "target": "to",
        "weight": 73
    }, {
        "source": "i",
        "target": "have",
        "weight": 72
    }, {
        "source": "this",
        "target": "is",
        "weight": 72
    }, {
        "source": "she",
        "target": "had",
        "weight": 72
    }, {
        "source": "dont",
        "target": "you",
        "weight": 72
    }, {
        "source": "harry",
        "target": "saw",
        "weight": 71
    }, {
        "source": "wanted",
        "target": "to",
        "weight": 71
    }, {
        "source": "at",
        "target": "his",
        "weight": 70
    }, {
        "source": "asked",
        "target": "harry",
        "weight": 70
    }, {
        "source": "it",
        "target": "to",
        "weight": 70
    }, {
        "source": "to",
        "target": "come",
        "weight": 70
    }, {
        "source": "in",
        "target": "front",
        "weight": 69
    }, {
        "source": "that",
        "target": "harry",
        "weight": 69
    }, {
        "source": "a",
        "target": "moment",
        "weight": 68
    }, {
        "source": "but",
        "target": "i",
        "weight": 68
    }, {
        "source": "to",
        "target": "make",
        "weight": 68
    }, {
        "source": "to",
        "target": "a",
        "weight": 68
    }, {
        "source": "if",
        "target": "he",
        "weight": 68
    }, {
        "source": "the",
        "target": "darkness",
        "weight": 67
    }, {
        "source": "the",
        "target": "way",
        "weight": 67
    }, {
        "source": "of",
        "target": "her",
        "weight": 67
    }, {
        "source": "you",
        "target": "were",
        "weight": 67
    }, {
        "source": "into",
        "target": "a",
        "weight": 67
    }, {
        "source": "with",
        "target": "his",
        "weight": 67
    }, {
        "source": "up",
        "target": "and",
        "weight": 67
    }, {
        "source": "we",
        "target": "are",
        "weight": 67
    }, {
        "source": "knew",
        "target": "that",
        "weight": 67
    }, {
        "source": "it",
        "target": "said",
        "weight": 66
    }, {
        "source": "dumbledore",
        "target": "had",
        "weight": 66
    }, {
        "source": "i",
        "target": "am",
        "weight": 65
    }, {
        "source": "at",
        "target": "harry",
        "weight": 65
    }, {
        "source": "his",
        "target": "face",
        "weight": 65
    }, {
        "source": "his",
        "target": "voice",
        "weight": 65
    }, {
        "source": "harry",
        "target": "looked",
        "weight": 65
    }, {
        "source": "harry",
        "target": "it",
        "weight": 65
    }, {
        "source": "the",
        "target": "back",
        "weight": 64
    }, {
        "source": "at",
        "target": "once",
        "weight": 64
    }, {
        "source": "that",
        "target": "you",
        "weight": 64
    }, {
        "source": "rowling",
        "target": "the",
        "weight": 64
    }, {
        "source": "off",
        "target": "the",
        "weight": 64
    }, {
        "source": "and",
        "target": "now",
        "weight": 63
    }, {
        "source": "it",
        "target": "would",
        "weight": 63
    }, {
        "source": "had",
        "target": "never",
        "weight": 63
    }, {
        "source": "onto",
        "target": "the",
        "weight": 63
    }, {
        "source": "tried",
        "target": "to",
        "weight": 62
    }, {
        "source": "the",
        "target": "last",
        "weight": 61
    }, {
        "source": "the",
        "target": "elder",
        "weight": 61
    }, {
        "source": "each",
        "target": "other",
        "weight": 61
    }, {
        "source": "his",
        "target": "feet",
        "weight": 61
    }, {
        "source": "that",
        "target": "she",
        "weight": 61
    }, {
        "source": "down",
        "target": "the",
        "weight": 61
    }, {
        "source": "about",
        "target": "the",
        "weight": 61
    }, {
        "source": "invisibility",
        "target": "cloak",
        "weight": 61
    }, {
        "source": "supposed",
        "target": "to",
        "weight": 61
    }, {
        "source": "the",
        "target": "ground",
        "weight": 60
    }, {
        "source": "the",
        "target": "goblin",
        "weight": 60
    }, {
        "source": "wand",
        "target": "and",
        "weight": 60
    }, {
        "source": "what",
        "target": "he",
        "weight": 60
    }, {
        "source": "death",
        "target": "eater",
        "weight": 60
    }, {
        "source": "and",
        "target": "she",
        "weight": 59
    }, {
        "source": "was",
        "target": "still",
        "weight": 59
    }, {
        "source": "know",
        "target": "what",
        "weight": 59
    }, {
        "source": "across",
        "target": "the",
        "weight": 59
    }, {
        "source": "elder",
        "target": "wand",
        "weight": 59
    }, {
        "source": "the",
        "target": "end",
        "weight": 58
    }, {
        "source": "the",
        "target": "locket",
        "weight": 58
    }, {
        "source": "the",
        "target": "moment",
        "weight": 58
    }, {
        "source": "the",
        "target": "castle",
        "weight": 58
    }, {
        "source": "a",
        "target": "small",
        "weight": 58
    }, {
        "source": "his",
        "target": "hand",
        "weight": 58
    }, {
        "source": "you",
        "target": "said",
        "weight": 58
    }, {
        "source": "to",
        "target": "keep",
        "weight": 58
    }, {
        "source": "under",
        "target": "the",
        "weight": 58
    }, {
        "source": "think",
        "target": "you",
        "weight": 58
    }, {
        "source": "and",
        "target": "there",
        "weight": 57
    }, {
        "source": "top",
        "target": "of",
        "weight": 57
    }, {
        "source": "away",
        "target": "from",
        "weight": 57
    }, {
        "source": "her",
        "target": "wand",
        "weight": 57
    }, {
        "source": "the",
        "target": "one",
        "weight": 56
    }, {
        "source": "of",
        "target": "him",
        "weight": 56
    }, {
        "source": "at",
        "target": "her",
        "weight": 56
    }, {
        "source": "at",
        "target": "last",
        "weight": 56
    }, {
        "source": "and",
        "target": "they",
        "weight": 56
    }, {
        "source": "as",
        "target": "it",
        "weight": 56
    }, {
        "source": "harry",
        "target": "felt",
        "weight": 56
    }, {
        "source": "from",
        "target": "his",
        "weight": 56
    }, {
        "source": "look",
        "target": "at",
        "weight": 56
    }, {
        "source": "her",
        "target": "in",
        "weight": 56
    }, {
        "source": "said",
        "target": "and",
        "weight": 55
    }, {
        "source": "up",
        "target": "at",
        "weight": 55
    }, {
        "source": "of",
        "target": "sight",
        "weight": 54
    }, {
        "source": "then",
        "target": "he",
        "weight": 54
    }, {
        "source": "as",
        "target": "a",
        "weight": 54
    }, {
        "source": "it",
        "target": "he",
        "weight": 54
    }, {
        "source": "will",
        "target": "be",
        "weight": 54
    }, {
        "source": "harry",
        "target": "ron",
        "weight": 54
    }, {
        "source": "to",
        "target": "them",
        "weight": 54
    }, {
        "source": "had",
        "target": "a",
        "weight": 54
    }, {
        "source": "had",
        "target": "just",
        "weight": 54
    }, {
        "source": "dont",
        "target": "know",
        "weight": 54
    }, {
        "source": "mr",
        "target": "weasley",
        "weight": 54
    }, {
        "source": "had",
        "target": "to",
        "weight": 53
    }, {
        "source": "im",
        "target": "sorry",
        "weight": 53
    }, {
        "source": "the",
        "target": "boy",
        "weight": 52
    }, {
        "source": "the",
        "target": "great",
        "weight": 52
    }, {
        "source": "for",
        "target": "him",
        "weight": 52
    }, {
        "source": "said",
        "target": "lupin",
        "weight": 52
    }, {
        "source": "against",
        "target": "the",
        "weight": 52
    }, {
        "source": "upon",
        "target": "the",
        "weight": 52
    }, {
        "source": "looked",
        "target": "at",
        "weight": 52
    }, {
        "source": "godrics",
        "target": "hollow",
        "weight": 52
    }, {
        "source": "the",
        "target": "horcrux",
        "weight": 51
    }, {
        "source": "and",
        "target": "her",
        "weight": 51
    }, {
        "source": "on",
        "target": "a",
        "weight": 51
    }, {
        "source": "that",
        "target": "is",
        "weight": 51
    }, {
        "source": "that",
        "target": "had",
        "weight": 51
    }, {
        "source": "harry",
        "target": "knew",
        "weight": 51
    }, {
        "source": "more",
        "target": "than",
        "weight": 51
    }, {
        "source": "from",
        "target": "him",
        "weight": 51
    }, {
        "source": "side",
        "target": "of",
        "weight": 51
    }, {
        "source": "the",
        "target": "front",
        "weight": 50
    }, {
        "source": "the",
        "target": "invisibility",
        "weight": 50
    }, {
        "source": "a",
        "target": "great",
        "weight": 50
    }, {
        "source": "in",
        "target": "and",
        "weight": 50
    }, {
        "source": "and",
        "target": "voldemort",
        "weight": 50
    }, {
        "source": "be",
        "target": "able",
        "weight": 50
    }, {
        "source": "his",
        "target": "scar",
        "weight": 50
    }, {
        "source": "though",
        "target": "he",
        "weight": 50
    }, {
        "source": "up",
        "target": "to",
        "weight": 50
    }, {
        "source": "down",
        "target": "at",
        "weight": 50
    }, {
        "source": "a",
        "target": "bit",
        "weight": 49
    }, {
        "source": "as",
        "target": "if",
        "weight": 49
    }, {
        "source": "harry",
        "target": "i",
        "weight": 49
    }, {
        "source": "rowling",
        "target": "harry",
        "weight": 49
    }, {
        "source": "so",
        "target": "that",
        "weight": 49
    }, {
        "source": "him",
        "target": "with",
        "weight": 49
    }, {
        "source": "professor",
        "target": "mcgonagall",
        "weight": 49
    }, {
        "source": "dumbledore",
        "target": "and",
        "weight": 49
    }, {
        "source": "saw",
        "target": "the",
        "weight": 49
    }, {
        "source": "i",
        "target": "can",
        "weight": 48
    }, {
        "source": "i",
        "target": "didnt",
        "weight": 48
    }, {
        "source": "said",
        "target": "dumbledore",
        "weight": 48
    }, {
        "source": "into",
        "target": "his",
        "weight": 48
    }, {
        "source": "the",
        "target": "top",
        "weight": 47
    }, {
        "source": "he",
        "target": "wanted",
        "weight": 47
    }, {
        "source": "you",
        "target": "harry",
        "weight": 47
    }, {
        "source": "to",
        "target": "take",
        "weight": 47
    }, {
        "source": "to",
        "target": "know",
        "weight": 47
    }, {
        "source": "again",
        "target": "and",
        "weight": 47
    }, {
        "source": "table",
        "target": "the",
        "weight": 47
    }, {
        "source": "looked",
        "target": "around",
        "weight": 47
    }, {
        "source": "where",
        "target": "he",
        "weight": 47
    }, {
        "source": "hermione",
        "target": "had",
        "weight": 47
    }, {
        "source": "i",
        "target": "do",
        "weight": 46
    }, {
        "source": "the",
        "target": "kitchen",
        "weight": 46
    }, {
        "source": "might",
        "target": "have",
        "weight": 46
    }, {
        "source": "you",
        "target": "see",
        "weight": 46
    }, {
        "source": "them",
        "target": "and",
        "weight": 46
    }, {
        "source": "end",
        "target": "of",
        "weight": 46
    }, {
        "source": "do",
        "target": "it",
        "weight": 46
    }, {
        "source": "began",
        "target": "to",
        "weight": 46
    }, {
        "source": "i",
        "target": "cant",
        "weight": 45
    }, {
        "source": "a",
        "target": "long",
        "weight": 45
    }, {
        "source": "in",
        "target": "it",
        "weight": 45
    }, {
        "source": "asked",
        "target": "ron",
        "weight": 45
    }, {
        "source": "on",
        "target": "it",
        "weight": 45
    }, {
        "source": "said",
        "target": "the",
        "weight": 45
    }, {
        "source": "it",
        "target": "the",
        "weight": 45
    }, {
        "source": "to",
        "target": "tell",
        "weight": 45
    }, {
        "source": "time",
        "target": "the",
        "weight": 45
    }, {
        "source": "talk",
        "target": "to",
        "weight": 45
    }, {
        "source": "the",
        "target": "two",
        "weight": 44
    }, {
        "source": "the",
        "target": "window",
        "weight": 44
    }, {
        "source": "out",
        "target": "the",
        "weight": 44
    }, {
        "source": "of",
        "target": "their",
        "weight": 44
    }, {
        "source": "for",
        "target": "you",
        "weight": 44
    }, {
        "source": "harry",
        "target": "he",
        "weight": 44
    }, {
        "source": "not",
        "target": "do",
        "weight": 44
    }, {
        "source": "my",
        "target": "lord",
        "weight": 44
    }, {
        "source": "would",
        "target": "not",
        "weight": 44
    }, {
        "source": "before",
        "target": "he",
        "weight": 44
    }, {
        "source": "no",
        "target": "said",
        "weight": 44
    }, {
        "source": "what",
        "target": "you",
        "weight": 44
    }, {
        "source": "the",
        "target": "stairs",
        "weight": 43
    }, {
        "source": "at",
        "target": "it",
        "weight": 43
    }, {
        "source": "at",
        "target": "hogwarts",
        "weight": 43
    }, {
        "source": "beneath",
        "target": "the",
        "weight": 43
    }, {
        "source": "was",
        "target": "no",
        "weight": 43
    }, {
        "source": "had",
        "target": "the",
        "weight": 43
    }, {
        "source": "we",
        "target": "were",
        "weight": 43
    }, {
        "source": "where",
        "target": "the",
        "weight": 43
    }, {
        "source": "the",
        "target": "order",
        "weight": 42
    }, {
        "source": "the",
        "target": "night",
        "weight": 42
    }, {
        "source": "the",
        "target": "snake",
        "weight": 42
    }, {
        "source": "the",
        "target": "hall",
        "weight": 42
    }, {
        "source": "of",
        "target": "us",
        "weight": 42
    }, {
        "source": "in",
        "target": "which",
        "weight": 42
    }, {
        "source": "they",
        "target": "could",
        "weight": 42
    }, {
        "source": "and",
        "target": "as",
        "weight": 42
    }, {
        "source": "thought",
        "target": "harry",
        "weight": 42
    }, {
        "source": "it",
        "target": "with",
        "weight": 42
    }, {
        "source": "that",
        "target": "dumbledore",
        "weight": 42
    }, {
        "source": "to",
        "target": "try",
        "weight": 42
    }, {
        "source": "could",
        "target": "have",
        "weight": 42
    }, {
        "source": "hermione",
        "target": "s",
        "weight": 42
    }, {
        "source": "old",
        "target": "the",
        "weight": 42
    }, {
        "source": "i",
        "target": "had",
        "weight": 41
    }, {
        "source": "the",
        "target": "house",
        "weight": 41
    }, {
        "source": "and",
        "target": "saw",
        "weight": 41
    }, {
        "source": "and",
        "target": "down",
        "weight": 41
    }, {
        "source": "and",
        "target": "bill",
        "weight": 41
    }, {
        "source": "it",
        "target": "if",
        "weight": 41
    }, {
        "source": "to",
        "target": "say",
        "weight": 41
    }, {
        "source": "wand",
        "target": "at",
        "weight": 41
    }, {
        "source": "after",
        "target": "a",
        "weight": 41
    }, {
        "source": "any",
        "target": "of",
        "weight": 41
    }, {
        "source": "her",
        "target": "eyes",
        "weight": 41
    }, {
        "source": "close",
        "target": "to",
        "weight": 41
    }, {
        "source": "isnt",
        "target": "it",
        "weight": 41
    }, {
        "source": "dark",
        "target": "lord",
        "weight": 40
    }, {
        "source": "said",
        "target": "voldemort",
        "weight": 40
    }, {
        "source": "but",
        "target": "you",
        "weight": 40
    }, {
        "source": "he",
        "target": "asked",
        "weight": 40
    }, {
        "source": "that",
        "target": "i",
        "weight": 40
    }, {
        "source": "harry",
        "target": "did",
        "weight": 40
    }, {
        "source": "did",
        "target": "it",
        "weight": 40
    }, {
        "source": "over",
        "target": "his",
        "weight": 40
    }, {
        "source": "full",
        "target": "of",
        "weight": 40
    }, {
        "source": "now",
        "target": "he",
        "weight": 40
    }, {
        "source": "the",
        "target": "little",
        "weight": 39
    }, {
        "source": "out",
        "target": "a",
        "weight": 39
    }, {
        "source": "of",
        "target": "magic",
        "weight": 39
    }, {
        "source": "at",
        "target": "all",
        "weight": 39
    }, {
        "source": "asked",
        "target": "hermione",
        "weight": 39
    }, {
        "source": "was",
        "target": "ron",
        "weight": 39
    }, {
        "source": "it",
        "target": "seemed",
        "weight": 39
    }, {
        "source": "which",
        "target": "he",
        "weight": 39
    }, {
        "source": "here",
        "target": "in",
        "weight": 39
    }, {
        "source": "we",
        "target": "need",
        "weight": 39
    }, {
        "source": "must",
        "target": "be",
        "weight": 39
    }, {
        "source": "ron",
        "target": "to",
        "weight": 39
    }, {
        "source": "the",
        "target": "wall",
        "weight": 38
    }, {
        "source": "the",
        "target": "entrance",
        "weight": 38
    }, {
        "source": "a",
        "target": "wand",
        "weight": 38
    }, {
        "source": "he",
        "target": "turned",
        "weight": 38
    }, {
        "source": "not",
        "target": "know",
        "weight": 38
    }, {
        "source": "with",
        "target": "her",
        "weight": 38
    }, {
        "source": "back",
        "target": "into",
        "weight": 38
    }, {
        "source": "some",
        "target": "of",
        "weight": 38
    }, {
        "source": "is",
        "target": "a",
        "weight": 38
    }, {
        "source": "ought",
        "target": "to",
        "weight": 38
    }, {
        "source": "the",
        "target": "stone",
        "weight": 37
    }, {
        "source": "the",
        "target": "rest",
        "weight": 37
    }, {
        "source": "of",
        "target": "you",
        "weight": 37
    }, {
        "source": "of",
        "target": "three",
        "weight": 37
    }, {
        "source": "in",
        "target": "that",
        "weight": 37
    }, {
        "source": "was",
        "target": "in",
        "weight": 37
    }, {
        "source": "around",
        "target": "his",
        "weight": 37
    }, {
        "source": "as",
        "target": "well",
        "weight": 37
    }, {
        "source": "his",
        "target": "hands",
        "weight": 37
    }, {
        "source": "will",
        "target": "you",
        "weight": 37
    }, {
        "source": "harry",
        "target": "who",
        "weight": 37
    }, {
        "source": "to",
        "target": "look",
        "weight": 37
    }, {
        "source": "to",
        "target": "time",
        "weight": 37
    }, {
        "source": "told",
        "target": "you",
        "weight": 37
    }, {
        "source": "what",
        "target": "do",
        "weight": 37
    }, {
        "source": "dont",
        "target": "think",
        "weight": 37
    }, {
        "source": "hermione",
        "target": "was",
        "weight": 37
    }, {
        "source": "get",
        "target": "you",
        "weight": 37
    }, {
        "source": "the",
        "target": "others",
        "weight": 36
    }, {
        "source": "at",
        "target": "a",
        "weight": 36
    }, {
        "source": "be",
        "target": "a",
        "weight": 36
    }, {
        "source": "you",
        "target": "want",
        "weight": 36
    }, {
        "source": "rowling",
        "target": "i",
        "weight": 36
    }, {
        "source": "first",
        "target": "time",
        "weight": 36
    }, {
        "source": "could",
        "target": "see",
        "weight": 36
    }, {
        "source": "behind",
        "target": "them",
        "weight": 36
    }, {
        "source": "how",
        "target": "to",
        "weight": 36
    }, {
        "source": "inside",
        "target": "the",
        "weight": 36
    }, {
        "source": "fred",
        "target": "and",
        "weight": 36
    }, {
        "source": "the",
        "target": "whole",
        "weight": 35
    }, {
        "source": "the",
        "target": "harry",
        "weight": 35
    }, {
        "source": "the",
        "target": "elf",
        "weight": 35
    }, {
        "source": "of",
        "target": "light",
        "weight": 35
    }, {
        "source": "in",
        "target": "him",
        "weight": 35
    }, {
        "source": "at",
        "target": "ron",
        "weight": 35
    }, {
        "source": "and",
        "target": "out",
        "weight": 35
    }, {
        "source": "but",
        "target": "there",
        "weight": 35
    }, {
        "source": "with",
        "target": "you",
        "weight": 35
    }, {
        "source": "raised",
        "target": "his",
        "weight": 35
    }, {
        "source": "to",
        "target": "hermione",
        "weight": 35
    }, {
        "source": "nothing",
        "target": "but",
        "weight": 35
    }, {
        "source": "looked",
        "target": "up",
        "weight": 35
    }, {
        "source": "come",
        "target": "on",
        "weight": 35
    }, {
        "source": "sure",
        "target": "that",
        "weight": 35
    }, {
        "source": "thank",
        "target": "you",
        "weight": 35
    }, {
        "source": "i",
        "target": "did",
        "weight": 34
    }, {
        "source": "the",
        "target": "three",
        "weight": 34
    }, {
        "source": "of",
        "target": "what",
        "weight": 34
    }, {
        "source": "they",
        "target": "would",
        "weight": 34
    }, {
        "source": "snape",
        "target": "said",
        "weight": 34
    }, {
        "source": "was",
        "target": "now",
        "weight": 34
    }, {
        "source": "to",
        "target": "think",
        "weight": 34
    }, {
        "source": "to",
        "target": "leave",
        "weight": 34
    }, {
        "source": "looking",
        "target": "for",
        "weight": 34
    }, {
        "source": "unable",
        "target": "to",
        "weight": 34
    }, {
        "source": "face",
        "target": "the",
        "weight": 34
    }, {
        "source": "beside",
        "target": "the",
        "weight": 34
    }, {
        "source": "behind",
        "target": "him",
        "weight": 34
    }, {
        "source": "its",
        "target": "not",
        "weight": 34
    }, {
        "source": "youve",
        "target": "got",
        "weight": 34
    }, {
        "source": "luna",
        "target": "and",
        "weight": 34
    }, {
        "source": "the",
        "target": "truth",
        "weight": 33
    }, {
        "source": "the",
        "target": "thing",
        "weight": 33
    }, {
        "source": "and",
        "target": "was",
        "weight": 33
    }, {
        "source": "and",
        "target": "go",
        "weight": 33
    }, {
        "source": "was",
        "target": "sure",
        "weight": 33
    }, {
        "source": "his",
        "target": "mind",
        "weight": 33
    }, {
        "source": "his",
        "target": "heart",
        "weight": 33
    }, {
        "source": "he",
        "target": "pulled",
        "weight": 33
    }, {
        "source": "you",
        "target": "cant",
        "weight": 33
    }, {
        "source": "sound",
        "target": "of",
        "weight": 33
    }, {
        "source": "to",
        "target": "give",
        "weight": 33
    }, {
        "source": "had",
        "target": "taken",
        "weight": 33
    }, {
        "source": "had",
        "target": "no",
        "weight": 33
    }, {
        "source": "him",
        "target": "the",
        "weight": 33
    }, {
        "source": "him",
        "target": "as",
        "weight": 33
    }, {
        "source": "all",
        "target": "he",
        "weight": 33
    }, {
        "source": "must",
        "target": "have",
        "weight": 33
    }, {
        "source": "part",
        "target": "of",
        "weight": 33
    }, {
        "source": "gave",
        "target": "a",
        "weight": 33
    }, {
        "source": "what",
        "target": "happened",
        "weight": 33
    }, {
        "source": "hermione",
        "target": "at",
        "weight": 33
    }, {
        "source": "knew",
        "target": "what",
        "weight": 33
    }, {
        "source": "weve",
        "target": "got",
        "weight": 33
    }]
}